/* PROGRAMAS CONCORRENTES */
SELECT R.REQUEST_ID, R.CONCURRENT_PROGRAM_ID
, DECODE (R.DESCRIPTION, NULL, PT.USER_CONCURRENT_PROGRAM_NAME, R.DESCRIPTION||' ('||PT.USER_CONCURRENT_PROGRAM_NAME||')') PROGRAM 
, PB.CONCURRENT_PROGRAM_NAME
, R.ARGUMENT_TEXT
, PHASE_CODE 
, FLF.MEANING PHASE_CODE
, STATUS_CODE 
, FLS.MEANING STATUS_CODE
, TO_CHAR(R.REQUEST_DATE,'DD-MON-YYYY HH24:MI:SS') REQUEST_DATE
, U.USER_NAME REQUESTOR
, TO_CHAR(R.ACTUAL_START_DATE,'DD-MON-YYYY HH24:MI:SS') ACTUAL_START_DATE
, TO_CHAR(R.ACTUAL_COMPLETION_DATE,'DD-MON-YYYY HH24:MI:SS') ACTUAL_COMPLETION_DATE 
, TO_CHAR((R.ACTUAL_COMPLETION_DATE-R.ACTUAL_START_DATE)*1440,'99999.99') TEMPO
FROM APPS.FND_CONCURRENT_PROGRAMS_TL PT
, APPS.FND_CONCURRENT_PROGRAMS PB
, APPS.FND_USER U
, APPS.FND_PRINTER_STYLES_TL S
, APPS.FND_CONCURRENT_REQUESTS R
, APPS.FND_LOOKUPS FLF
, APPS.FND_LOOKUPS FLS
WHERE PB.APPLICATION_ID = R.PROGRAM_APPLICATION_ID
AND PB.CONCURRENT_PROGRAM_ID = R.CONCURRENT_PROGRAM_ID
AND PB.APPLICATION_ID = PT.APPLICATION_ID
AND PB.CONCURRENT_PROGRAM_ID = PT.CONCURRENT_PROGRAM_ID
AND PT.LANGUAGE = 'US' -- USERENV('LANG')
AND U.USER_ID = R.REQUESTED_BY
AND S.PRINTER_STYLE_NAME(+) = R.PRINT_STYLE
AND S.LANGUAGE(+) = 'US' -- USERENV('LANG')
AND FLF.LOOKUP_TYPE = 'CP_PHASE_CODE'
AND FLF.LOOKUP_CODE = R.PHASE_CODE
AND FLS.LOOKUP_TYPE = 'CP_STATUS_CODE'
AND FLS.LOOKUP_CODE = R.STATUS_CODE
-------- Alterar os ^Filtros abaixo conforme necessidade
AND PHASE_CODE = 'P' -- Pending
--AND PHASE_CODE != 'C' -- Completed
--AND PHASE_CODE = 'C' AND STATUS_CODE != 'X' 
--AND PHASE_CODE = 'C' AND STATUS_CODE = 'E' 
--AND TRUNC(REQUEST_DATE) >= TRUNC(SYSDATE)-1
--AND U.USER_NAME = 'BR_SCHEDULER'
--AND U.USER_NAME not in ('BR_SCHEDULER','SYSADMIN')
--AND USER_CONCURRENT_PROGRAM_NAME = 'Criar Contabilidade - Gerenciamento de Custos'
--AND USER_CONCURRENT_PROGRAM_NAME = 'Workflow Background Process'
--AND USER_CONCURRENT_PROGRAM_NAME = 'PO Output for Communication'
--AND USER_CONCURRENT_PROGRAM_NAME = 'XXPPG - Interface Inbound WMAS x Oracle EBS'
--AND USER_CONCURRENT_PROGRAM_NAME = 'XXPPG - ROMANEIO REMESSA DHL (Outbound)'
--AND USER_CONCURRENT_PROGRAM_NAME = 'PPG – Transferência de Estoque DHL'
--AND USER_CONCURRENT_PROGRAM_NAME = 'XXPPG - Relatório de Batimento de Saldo'
--AND USER_CONCURRENT_PROGRAM_NAME = 'XXPPG - ROMANEIO REMESSA DHL (Inbound)'
--AND USER_CONCURRENT_PROGRAM_NAME = 'XXPPGBR - Interface PC-Factory (Inbound)'
--AND USER_CONCURRENT_PROGRAM_NAME = 'XXPPG - Interface Outbound Oracle EBS x WMAS' AND ARGUMENT1 = '82.9'
--AND USER_CONCURRENT_PROGRAM_NAME = 'XXPPG - Interface Inbound WMAS x Oracle EBS' AND ARGUMENT1 = '81.1'
--AND USER_CONCURRENT_PROGRAM_NAME = 'XXPPG - Interface Inbound WMAS x Oracle EBS' AND ARGUMENT1 = '81.1'
--AND USER_CONCURRENT_PROGRAM_NAME = 'Credit Check Processor'
--AND USER_CONCURRENT_PROGRAM_NAME = 'Initialize Credit Summaries Table' 
--AND USER_CONCURRENT_PROGRAM_NAME = 'Autoinvoice Import Program'
--AND USER_CONCURRENT_PROGRAM_NAME = 'Autoinvoice Master Program'
--AND PB.CONCURRENT_PROGRAM_NAME = 'FNDRSSUB' -- XXPPG_Programa-mestre de NFFs Automáticas (Report Set)
--AND USER_CONCURRENT_PROGRAM_NAME like 'Refresh Case Folder Data Program'
--AND PB.CONCURRENT_PROGRAM_NAME = 'RAXMTR' AND ARGUMENT4 like 'GVT%'
--AND PB.CONCURRENT_PROGRAM_NAME = 'ALECDC' -- ... (Check Periodic Alert)
--AND PB.CONCURRENT_PROGRAM_NAME = 'WSHINTERFACES' 
--AND PB.CONCURRENT_PROGRAM_NAME = 'REQIMPORT' 
--AND PB.CONCURRENT_PROGRAM_NAME = 'GMFAACCP' -- Criar Contabilidade
--AND PB.CONCURRENT_PROGRAM_NAME = 'JLARAPAC' --- Criar Conta para AR e AP da América Latina
--AND ARGUMENT1 = 'OESTD' 
--AND ARGUMENT4 like 'BEL%' 
ORDER BY R.REQUEST_ID DESC
