
/* Formatted on 08/01/2016 16:07:17 (QP5 v5.227.12220.39724) */
SELECT DOC.CODIGOESTABELECIMENTO,
       DOC.CODIGODEPOSITANTE,
       DOC.CODIGOEMPRESA,
       DOC.TIPODOCUMENTO,
       DOC.SERIEDOCUMENTO,
       DOC.DOCUMENTOENTRADA AS NUMERODOCUMENTO,
       DOC.DATAEMISSAO,
       DOC.DATAMOVIMENTO,
       DOC.ESTADODOCUMENTO,
       DOC.NATUREZAOPERACAO,
       LOT.LOTEENTRADA,
       LOT.NUMEROLOTE,
       LOT.CODIGOPRODUTO,
       LOT.TIPOLOGISTICO,
       LOT.DADOLOGISTICO,
       SEQ.TIPOUC,
       SEQ.FATORTIPOUC,
       SEQ.LOTEENTRADASEQUENCIA,
       SEQ.CODIGOUA,
       SEQ.QUANTIDADEINICIAL,
       SEQ.QUANTIDADEATUAL,
       SEQ.QUANTIDADEBLOQUEADO,
       SEQ.LOTEFABRICACAO,
       SEQ.DATAFABRICACAO,
       SEQ.DATAVENCIMENTO,
       SEQ.LOTEGERAL,
       SEQ.CLASSEPRODUTO,
       DOC.CODIGOEMPRESADESTINO,
       CUA.ENDERECO AS ENDERECOUA,
       CUA.TIPOUA,
       CUA.LARGURA AS LARGURAUA,
       CUA.ALTURA AS ALTURAUA,
       CUA.PROFUNDIDADE AS PROFUNDIDADEUA,
       EDE.ETIQUETAENDERECO,
       PRO.DESCRICAOPRODUTO,
       PRO.CODIGOGRUPO,
       PRO.TIPOBAIXA,
       PRO.ATIVO,
       PRO.CLASSIFICACAOPRODUTO,
       PRO.CLASSIFICACAOPICKING,
       NVL (
          (SELECT SUM (RES.QUANTIDADERESERVA)
             FROM ENDERECORESERVA RES, COLETORMENSAGEM COL
            WHERE     RES.CODIGOESTABELECIMENTO = SEQ.CODIGOESTABELECIMENTO
                  AND RES.LOTEENTRADA = SEQ.LOTEENTRADA
                  AND RES.LOTEENTRADASEQUENCIA = SEQ.LOTEENTRADASEQUENCIA
                  AND RES.TIPORESERVA = 2
                  AND RES.QUANTIDADERESERVA > 0
                  AND RES.CODIGOEMPRESA = PRO.CODIGOEMPRESA
                  AND RES.CODIGOPRODUTO = PRO.CODIGOPRODUTO
                  AND RES.CODIGOESTABELECIMENTO = COL.CODIGOESTABELECIMENTO
                  AND RES.CODIGOMENSAGEM = COL.CODIGOMENSAGEM
                  AND COL.CODIGOTAREFA <> 170),
          0)
          AS QUANTIDADERESERVA,
       EDE.DISPONIVELSAIDA
  FROM wmas.DOCUMENTOENTRADA DOC,
       wmas.LOTEENTRADA LOT,
       wmas.LOTEENTRADASEQUENCIA SEQ,
       wmas.UA CUA,
       wmas.ENDERECO EDE,
       apps.PRODUTO PRO
 WHERE     DOC.ESTADODOCUMENTO IN (23, 25)
       AND LOT.CODIGOEMPRESA = DOC.CODIGOEMPRESA
       AND LOT.TIPODOCUMENTO = DOC.TIPODOCUMENTO
       AND LOT.SERIEDOCUMENTO = DOC.SERIEDOCUMENTO
       AND LOT.DOCUMENTOENTRADA = DOC.DOCUMENTOENTRADA
       AND SEQ.CODIGOESTABELECIMENTO = LOT.CODIGOESTABELECIMENTO
       AND SEQ.LOTEENTRADA = LOT.LOTEENTRADA
       AND CUA.CODIGOESTABELECIMENTO = SEQ.CODIGOESTABELECIMENTO
       AND CUA.CODIGOUA = SEQ.CODIGOUA
       AND EDE.CODIGOESTABELECIMENTO = CUA.CODIGOESTABELECIMENTO
       AND EDE.ENDERECO = CUA.ENDERECO
       AND PRO.CODIGOEMPRESA = LOT.CODIGOMATRIZ
       AND PRO.CODIGOPRODUTO = LOT.CODIGOPRODUTO;
       
       
       XXPPG_INV_GAPR117_PKG