SELECT *
      FROM APPS.HZ_CONTACT_POINTS      HCP1
          ,APPS.RA_CUSTOMER_TRX_ALL    RCT
          ,APPS.HZ_PARTIES             HP
         , APPS.HZ_PARTY_SITES         HPS1
         , APPS.HZ_CUST_SITE_USES_ALL  HCSU1
         , APPS.HZ_CUST_ACCT_SITES_ALL HCAS1
     WHERE HCP1.OWNER_TABLE_NAME      = 'HZ_PARTY_SITES'
       AND HCP1.CONTACT_POINT_TYPE    = 'EMAIL'
       AND HCP1.CONTACT_POINT_PURPOSE = 'MAIL LAUDO'
       AND HCP1.STATUS                = 'A'
       AND HCP1.OWNER_TABLE_ID        = HPS1.PARTY_SITE_ID
       AND HCSU1.CUST_ACCT_SITE_ID    = HCAS1.CUST_ACCT_SITE_ID
       AND HCAS1.PARTY_SITE_ID        = HPS1.PARTY_SITE_ID
       AND HPS1.PARTY_ID              = hp.party_id
       AND HCSU1.SITE_USE_ID          = RCT.BILL_TO_SITE_USE_ID 




