--BEGIN APPS.MO_GLOBAL.SET_POLICY_CONTEXT('S', 82 ); END;
SELECT L01.MEANING    CAMPO_1,
       HCA.ACCOUNT_NUMBER||HPS.PARTY_SITE_NAME CAMPO_2, --Código do Cliente
       HZP.PARTY_NAME                      CAMPO_10,    --Razão Social do Cliente
       L12.MEANING                         CAMPO_12,    --Grupo Cliente contabil 
(SELECT GCC.SEGMENT6 ||' - '||(
SELECT FFVT.FLEX_VALUE_MEANING
  FROM APPS.FND_FLEX_VALUES     FFVV
     , APPS.FND_FLEX_VALUES_TL  FFVT
     , APPS.FND_FLEX_VALUE_SETS FFVS 
 WHERE FFVS.FLEX_VALUE_SET_ID = FFVV.FLEX_VALUE_SET_ID
   AND FFVV.FLEX_VALUE_ID = FFVT.FLEX_VALUE_ID 
   AND FFVV.FLEX_VALUE = GCC.SEGMENT6
   AND FFVS.FLEX_VALUE_SET_NAME = 'XXGL_PRODUCT_LINE'
   AND FFVT.LANGUAGE = 'PTB')
  FROM APPS.GL_CODE_COMBINATIONS_KFV GCC
     , APPS.HZ_CUST_SITE_USES_ALL  HSUA1
 WHERE HSUA1.GL_ID_REV = GCC.CODE_COMBINATION_ID
   AND HSUA1.CUST_ACCT_SITE_ID = HSUA.CUST_ACCT_SITE_ID
       APPS.HZ_CUST_ACCOUNTS       HCA,
   AND HSUA1.SITE_USE_CODE = 'BILL_TO'
   AND HSUA1.STATUS = 'A') CAMPO_13 --Product Line Atual
  FROM APPS.HZ_PARTIES             HZP,
       APPS.HZ_PARTY_SITES         HPS,
       APPS.HZ_CUST_ACCT_SITES_ALL HCASA,
       APPS.HZ_LOCATIONS           HL,
       APPS.FND_LOOKUP_VALUES      L01, 
       APPS.FND_LOOKUP_VALUES      L12,(
SELECT CCB.CUST_ACCT_SITE_ID,
       CCB.SALES_CHANNEL,
       CCB.SALESREP_ID,
       CCB.SITE_USE_ID SITE_USE_ID
  FROM XXPPG.XXPPG_OM_CROSS_BU_ALL CCB
UNION
SELECT HSUA.CUST_ACCT_SITE_ID,
       NVL(CB.SALES_CHANNEL,HSUA.ATTRIBUTE1),
       NVL(CB.SALESREP_ID,  HSUA.PRIMARY_SALESREP_ID),
       HSUA.SITE_USE_ID
  FROM APPS.HZ_CUST_SITE_USES_ALL HSUA
     , XXPPG.XXPPG_OM_CROSS_BU_ALL CB
 WHERE HSUA.SITE_USE_CODE = 'SHIP_TO'
   AND HSUA.SITE_USE_ID   = CB.SITE_USE_ID(+)) HSUA
 WHERE 1=1
   AND HCASA.CUST_ACCT_SITE_ID = HSUA.CUST_ACCT_SITE_ID
   AND HCASA.CUST_ACCOUNT_ID  = HCA.CUST_ACCOUNT_ID
   AND HCASA.PARTY_SITE_ID  = HPS.PARTY_SITE_ID
--   AND HCA.ACCOUNT_NUMBER||HPS.PARTY_SITE_NAME IN ('0081977310005-04','0864665130001-08','0838829360001-10')
--   AND HCASA.CUST_ACCT_SITE_ID = 1248
--   LIKE 'E000046'
   AND HPS.LOCATION_ID      = HL.LOCATION_ID
   AND HZP.PARTY_ID         = HCA.PARTY_ID
   AND HZP.PARTY_ID         = HPS.PARTY_ID
   AND HSUA.SALES_CHANNEL   = L01.LOOKUP_CODE(+)
   
   AND L01.MEANING          = 'REF'
   
   AND L01.LOOKUP_TYPE(+)   ='SALES_CHANNEL'
   AND L01.LANGUAGE(+)      = USERENV('LANG')
   AND HZP.ATTRIBUTE2       = L12.LOOKUP_CODE(+)
   AND L12.LOOKUP_TYPE(+)   ='PPG_BR_AR_GRP_CLIENTE'
   AND L12.LANGUAGE(+)      = USERENV('LANG')
ORDER BY 1, --REPLACE(HCASA.ORIG_SYSTEM_REFERENCE,'EMS_',''),
       HZP.PARTY_NAME,
       HPS.PARTY_SITE_NAME,
       HCASA.CUST_ACCT_SITE_ID