select * from apps.user$;

DBA_SYS_PRIVS
DBA_TAB_PRIVS
DBA_ROLE_PRIVS

SELECT USERNAME,
       CREATED,       
       LAST_LOGIN,
       PASSWORD_CHANGE_DATE 
  FROM dba_users
 WHERE USERNAME IN ('FOCUS_USER',
'APPLSYSPUB',
'BIZTALK_LA_USER',
'FOCUS_USER',
'GPS_USER',
'MDM_USER',
'NAORACLEUSERREQUEST',
'SFW_SUPPORT',
'SSPL_USER',
'UNIVERSE',
'XXPPG_DATALAKE_LA',
'XXPPG_INTERFACE_FRETE',
'XXPPG_INTERFACE_GSC',
'XXPPG_INTERFACE_SAP',
'XXPPG_INTERFACE_ZILLIANT',
'AM_AGENT',
'BATCH_TRACKER_USER');

INFORMATICA_USER/Rosales Alvarado Daniel Alejandro
       