SELECT segment1,
       ORGANIZATION_CODE,
       CROSS_REFERENCE
  FROM APPS.MTL_CROSS_REFERENCES_V XRF,
       APPS.MTL_SYSTEM_ITEMS_B MSI
 WHERE xrf.CROSS_REFERENCE_TYPE = 'DUN14'               AND
       XRF.inventory_item_id    = MSI.INVENTORY_ITEM_ID AND
       MSI.ORGANIZATION_ID      = 92