INSERT INTO MTL_TRANSACTION_LOTS_INTERFACE
  (TRANSACTION_INTERFACE_ID,
   SOURCE_CODE,
   SOURCE_LINE_ID,
   LOT_NUMBER,
   LOT_EXPIRATION_DATE,
   TRANSACTION_QUANTITY,
   STATUS_ID,
   LAST_UPDATE_DATE,
   LAST_UPDATED_BY,
   CREATION_DATE,
   CREATED_BY)

  SELECT TRANSACTION_INTERFACE_ID,
          SOURCE_CODE,
          SOURCE_LINE_ID,
          '0130323', --LOT_NUMBER,
          '05/04/2014', --LOT_EXPIRATION_DATE,
          TRANSACTION_QUANTITY,
          20, --STATUS_ID,
          LAST_UPDATE_DATE,
          LAST_UPDATED_BY,
          CREATION_DATE,
          CREATED_BY
      FROM APPS.MTL_TRANSACTIONS_INTERFACE_V
    WHERE TRANSACTION_INTERFACE_ID = 62055450