SELECT MSI.ITEM_TYPE               "Nome Template",
--       MSI.INVENTORY_ITEM_ID,
--       MSI.CREATION_DATE           "Data da CriaÁ„o",
       MSI.SEGMENT1                "CÛdigo do Item",
       MSI.PURCHASING_ITEM_FLAG      Item_Comprado, 
       MSI.PURCHASING_ENABLED_FLAG   Habilitado_Compra,
--       MSI.INVENTORY_ITEM_STATUS_CODE "Status do Item",
       MP.ORGANIZATION_CODE        "CÛdigo da OrganizaÁ„o",
       TRANSLATE(msi.description,'ABCDEFGHIJKLMNOPQRSTUWVXYZabcdefghijklmnopqrstuwvxyz01234567890—¡…Õ”⁄¿»Ã“Ÿ¬ Œ‘€√’ƒÀœ÷‹«Ò·ÈÌÛ˙‡ËÏÚ˘‚ÍÓÙ˚„ı‰ÎÔˆ¸Áñ∫™≤∞.-!"''`#$%().:[/]{}®+???ø;ß&¥*<>'
                                             ,'ABCDEFGHIJKLMNOPQRSTUWVXYZabcdefghijklmnopqrstuwvxyz01234567890NAEIOUAEIOUAEIOUAOAEIOUCnaeiouaeiouaeiouaoaeiouc-') "DescriÁ„o Curta do Item",
--       TRANSLATE(MST.LONG_DESCRIPTION,'ABCDEFGHIJKLMNOPQRSTUWVXYZabcdefghijklmnopqrstuwvxyz01234567890—¡…Õ”⁄¿»Ã“Ÿ¬ Œ‘€√’ƒÀœ÷‹«Ò·ÈÌÛ˙‡ËÏÚ˘‚ÍÓÙ˚„ı‰ÎÔˆ¸Áñ∫™≤∞.-!"''`#$%().:[/]{}®+???ø;ß&¥*<>'
--                                             ,'ABCDEFGHIJKLMNOPQRSTUWVXYZabcdefghijklmnopqrstuwvxyz01234567890NAEIOUAEIOUAEIOUAOAEIOUCnaeiouaeiouaeiouaoaeiouc-') "DescriÁ„o Curta do Item",
                                             
       MSI.PRIMARY_UOM_CODE        "Unidade de Medida Princip al",
       MSI.PRIMARY_UNIT_OF_MEASURE "Unidade de Medida Principal_I",
       MSI.TRACKING_QUANTITY_IND   "Rastreamento",
       MSI.SECONDARY_UOM_CODE      "Unidade de Medida Secund·ria",
       MSI.SECONDARY_DEFAULT_IND   "Padr„o",
       MSI.SHELF_LIFE_CODE         "ExpiraÁ„o Lote",
       MSI.SHELF_LIFE_DAYS         "Dias de Estocagem",
       MSI.DEFAULT_LOT_STATUS_ID   "Status do Lote Padr„o",
       (SELECT CONCATENATED_SEGMENTS FROM APPS.GL_CODE_COMBINATIONS_KFV GCC WHERE CODE_COMBINATION_ID = MSI.COST_OF_SALES_ACCOUNT) "Conta do Custo das Merc Vend",
       MSI.MUST_USE_APPROVED_VENDOR_FLAG "Usar Fornecedor Aprovado",
       (SELECT DISTINCT FULL_NAME FROM apps.per_people_f PPF WHERE PPF.PERSON_ID = MSI.BUYER_ID AND ROWNUM = 1) "Comprador Default",
       MSI.LIST_PRICE_PER_UNIT           "Lista de PreÁos",
       (SELECT CONCATENATED_SEGMENTS FROM APPS.GL_CODE_COMBINATIONS_KFV GCC WHERE CODE_COMBINATION_ID = MSI.EXPENSE_ACCOUNT) "Conta de Despesas",
       (SELECT SEGMENT1||'.'||SEGMENT2 FROM APPS.FA_CATEGORIES_VL WHERE CATEGORY_ID = MSI.ASSET_CATEGORY_ID) "Categoria do Ativo",
       MSI.QTY_RCV_EXCEPTION_CODE   "Control de Qtde de Receb Exc",
       MSI.QTY_RCV_TOLERANCE        "Toler‚ncia",
       MSI.WEIGHT_UOM_CODE          "Unidade de Medida de Peso",
       MSI.UNIT_WEIGHT              "Peso da unidade",
       MSI.VOLUME_UOM_CODE          "Unidade de Medida de Volume",
       MSI.UNIT_VOLUME              "Volume da Unidade",
       MSI.DIMENSION_UOM_CODE       "Unidade de Medida Dimensıes",
       MSI.UNIT_LENGTH              "Comprimento",
       MSI.UNIT_WIDTH               "Largura",
       MSI.UNIT_HEIGHT              "Altura",
       MSI.PLANNER_CODE             "Planejador",
       MSI.MIN_MINMAX_QUANTITY      "MÌnimo",
       MSI.MAX_MINMAX_QUANTITY      "M·ximo",
       MSI.MINIMUM_ORDER_QUANTITY   "Quantidade MÌnima Ordem",
       MSI.MAXIMUM_ORDER_QUANTITY   "Quantidade M·xima Ordem",
       MSI.MRP_SAFETY_STOCK_CODE    "Estoque de SeguranÁa MÈtodo",
       MSI.SAFETY_STOCK_BUCKET_DAYS "Dias do PerÌodo",
       MSI.MRP_SAFETY_STOCK_PERCENT "Percentual",
       MSI.FIXED_ORDER_QUANTITY     "Qtd. Ordem Fixa",
       MSI.FIXED_DAYS_SUPPLY        "Suprimento de Dias Fixos",
       MSI.FIXED_LOT_MULTIPLIER     "Multiplicador de Lote Fixo",
       MSI.PLANNING_EXCEPTION_SET   "Conjunto de ExceÁıes",
       MSI.ACCEPTABLE_EARLY_DAYS    "Dias aceit·veis de Antecip",
       MSI.PLANNING_TIME_FENCE_CODE "Per. Congelamento Planej",
       MSI.PLANNING_TIME_FENCE_DAYS "Per.Congelamento Planej. Dias",
       MSI.DEMAND_TIME_FENCE_CODE   "Per. Congelamento Demanda",
       MSI.DEMAND_TIME_FENCE_DAYS   "Dias do Per. Cong Demanda",
       MSI.PREPROCESSING_LEAD_TIME  "PrÈ-Processamento",
       MSI.FULL_LEAD_TIME           "Processando",
       MSI.POSTPROCESSING_LEAD_TIME "PÛs-Processamento",
       (SELECT CONCATENATED_SEGMENTS FROM APPS.GL_CODE_COMBINATIONS_KFV GCC WHERE CODE_COMBINATION_ID = MSI.SALES_ACCOUNT) "Conta de Vendas",
       MSI.PROCESS_SUPPLY_SUBINVENTORY "Subinvent·rio de Suprimento",
       (SELECT CONCATENATED_SEGMENTS FROM APPS.MTL_ITEM_LOCATIONS_KFV WHERE INVENTORY_LOCATION_ID = MSI.PROCESS_SUPPLY_LOCATOR_ID) "EndereÁo de Suprimentos",
       MSI.PROCESS_YIELD_SUBINVENTORY  "Subinv de Aproveitamento",
       (SELECT CONCATENATED_SEGMENTS FROM APPS.MTL_ITEM_LOCATIONS_KFV WHERE INVENTORY_LOCATION_ID = MSI.PROCESS_YIELD_LOCATOR_ID) "EndereÁo de Aproveitamento",
       MSI.GLOBAL_ATTRIBUTE8           "Aplic do Item de Invent",
       MSI.GLOBAL_ATTRIBUTE2           "Classe da Cond da TransaÁ„o",
       MSI.GLOBAL_ATTRIBUTE3           "Origem do Item",
       MSI.GLOBAL_ATTRIBUTE4           "Tipo Fiscal do Item",
       MSI.GLOBAL_ATTRIBUTE6           "SituaÁ„o Trib Estadual",
       MSI.GLOBAL_ATTRIBUTE5           "SituaÁ„o Trib Federal",
       MSI.GLOBAL_ATTRIBUTE10          "Codigo EAN Unidade",
       INVENTARIO.CATEGORIA            CATEG_INVENTARIO,
       COMPRA.CATEGORIA CATEG_COMPRA,
       FISCAL_CLASSIFICATION.CATEGORIA CATEG_FISCAL_CLASSIFICATION,       
       CUSTO_OPM.CATEGORIA             CAT_EGCUSTO,
--       'N' "ITEM DE ENGENHARIA",
       MSI.ATTRIBUTE9                  "Peso Bruto"
--       (SELECT SEGMENT1 CATALOGO FROM APPS.MTL_ITEM_CATALOG_GROUPS_VL  WHERE ITEM_CATALOG_GROUP_ID = MSI.ITEM_CATALOG_GROUP_ID ) CATALOGO

  FROM APPS.MTL_SYSTEM_ITEMS MSI,
       APPS.MTL_PARAMETERS MP,
       APPS.MTL_SYSTEM_ITEMS_TL MST,
       (SELECT MIC.INVENTORY_ITEM_ID,
               MIC.ORGANIZATION_ID,
               MIC.CATEGORY_SET_NAME,
               MIC.CATEGORY_CONCAT_SEGS CATEGORIA
          FROM APPS.MTL_ITEM_CATEGORIES_V MIC, APPS.MTL_CATEGORIES_V MC
         WHERE MC.CATEGORY_ID = MIC.CATEGORY_ID
           AND MIC.CATEGORY_SET_NAME IN ('Categoria de Custo')) CUSTO_OPM,
       (SELECT MIC.INVENTORY_ITEM_ID,
               MIC.ORGANIZATION_ID,
               MIC.CATEGORY_SET_NAME,
               MIC.CATEGORY_CONCAT_SEGS CATEGORIA
          FROM APPS.MTL_ITEM_CATEGORIES_V MIC, APPS.MTL_CATEGORIES_V MC
         WHERE MC.CATEGORY_ID = MIC.CATEGORY_ID
           AND MIC.CATEGORY_SET_NAME IN ('Inventory')) INVENTARIO,
       (SELECT MIC.INVENTORY_ITEM_ID,
               MIC.ORGANIZATION_ID,
               MIC.CATEGORY_SET_NAME,
               MIC.CATEGORY_CONCAT_SEGS CATEGORIA
          FROM APPS.MTL_ITEM_CATEGORIES_V MIC, APPS.MTL_CATEGORIES_V MC
         WHERE MC.CATEGORY_ID = MIC.CATEGORY_ID
           AND MIC.CATEGORY_SET_NAME IN ('FISCAL_CLASSIFICATION')) FISCAL_CLASSIFICATION,
       (SELECT MIC.INVENTORY_ITEM_ID,
               MIC.ORGANIZATION_ID,
               MIC.CATEGORY_SET_NAME,
               MIC.CATEGORY_CONCAT_SEGS CATEGORIA
          FROM APPS.MTL_ITEM_CATEGORIES_V MIC, APPS.MTL_CATEGORIES_V MC
         WHERE MC.CATEGORY_ID = MIC.CATEGORY_ID
           AND MIC.CATEGORY_SET_NAME IN ('Compras')) COMPRA

 WHERE 1 = 1
   AND MSI.ORGANIZATION_ID = MP.ORGANIZATION_ID
   AND MSI.ORGANIZATION_ID = MST.ORGANIZATION_ID
   AND MSI.INVENTORY_ITEM_ID = MST.INVENTORY_ITEM_ID
   AND MST.LANGUAGE = 'PTB'
--   AND MSI.ITEM_TYPE NOT IN('GEQ_SERVICO','SERVICO')
   AND MSI.ORGANIZATION_ID = CUSTO_OPM.ORGANIZATION_ID(+)
   AND MSI.INVENTORY_ITEM_ID = CUSTO_OPM.INVENTORY_ITEM_ID(+)
   AND MSI.ORGANIZATION_ID = INVENTARIO.ORGANIZATION_ID(+)
   AND MSI.INVENTORY_ITEM_ID = INVENTARIO.INVENTORY_ITEM_ID(+)
   AND MSI.ORGANIZATION_ID = FISCAL_CLASSIFICATION.ORGANIZATION_ID(+)
   AND MSI.INVENTORY_ITEM_ID = FISCAL_CLASSIFICATION.INVENTORY_ITEM_ID(+)
   AND MSI.ORGANIZATION_ID = COMPRA.ORGANIZATION_ID(+)
   AND MSI.INVENTORY_ITEM_ID = COMPRA.INVENTORY_ITEM_ID(+)
--   AND (SELECT CONCATENATED_SEGMENTS FROM APPS.GL_CODE_COMBINATIONS_KFV GCC WHERE CODE_COMBINATION_ID = MSI.EXPENSE_ACCOUNT) LIKE '%58000%'
--   AND SEGMENT1 LIKE '1000%'
   --AND MSI.ITEM_TYPE NOT IN('RECURSOS_MANUTENCAO', 'GEQ_RECURSOS_MANUTENCAO','VEICULOS_OTM', 'AG', 'AA','GEQ_VEICULOS_OTM','GEQ_SERVICO','SERVICO','PH')
--   AND MP.ORGANIZATION_CODE NOT IN('E01','E02','E03','E04','C01','C02','C03','C04','C05','C06')
--   and MSI.ATTRIBUTE1 IN('5415246700')--,'4502003246')
   --AND MP.ORGANIZATION_CODE IN('057')
--   AND MSI.ATTRIBUTE19 = 'Y'
--   AND COMPRA.CATEGORIA  = '000.057.000.309' --'000.030.000.061'
-- AND CLASSE_GL_OPM.CATEGORIA IN('MERCADORIA REVENDA','PRODUTO ACABADO')
--   AND MP.ORGANIZATION_CODE IN('022','ESP','023','024','025','026','027','028','029','030','031','032')
--   AND MSI.BUYER_ID = 4279
--AND MSI.ATTRIBUTE1 IN('5810120373','7590655024','7590655083','7590655202','8600010029')
  --AND MSI.SEGMENT1 IN('1000000130')
--AND MP.ORGANIZATION_CODE IN('037','038','039','040','041','042','043','044','045','046','047','048','049','050','051','052','053','054','055','056','057','058','059','060','061','062','063','064','065','066','067','068','069','070','071','072','073','074','075','076','077','089','090','091','092','093','094','095','096','001','002','003','004','005','006','007','008','009','081','082','083','084','085','086','087','088')
--AND CLASSE_GL_OPM.CATEGORIA IN('MERCADORIA REVENDA','PRODUTO ACABADO')
--AND MSI.PRIMARY_UOM_CODE <> MSI.ATTRIBUTE18
--AND MSI.ATTRIBUTE1 = '8220002482'--IN()
--AND MSI.INVENTORY_ITEM_ID = 5226615
--AND MP.ORGANIZATION_ID = 814
--  AND MSI.ATTRIBUTE9 LIKE '%.%'

ORDER BY 2,3
