SELECT msi.segment1,
       msi.description,
       MP.ORGANIZATION_CODE,
       INVENTARIO.CATEGORIA            CATEG_INVENTARIO,
       COMPRA.CATEGORIA CATEG_COMPRA,
       FISCAL_CLASSIFICATION.CATEGORIA CATEG_FISCAL_CLASSIFICATION,       
       CUSTO_OPM.CATEGORIA             CAT_EGCUSTO,
       pun.UN_NUMBER,
       pun.DESCRIPTION,
      (select fv.description 
         from apps.FND_FLEX_VALUES_VL fv 
        where fv.flex_value_set_id = 1016123 AND
              fv.flex_value = inventario.segment3) description
--
  FROM APPS.MTL_SYSTEM_ITEMS MSI,
       APPS.MTL_PARAMETERS MP,
       APPS.MTL_SYSTEM_ITEMS_TL MST,
       APPS.PO_UN_NUMBERS_VL pun,
       (SELECT MIC.INVENTORY_ITEM_ID,
               MIC.ORGANIZATION_ID,
               MIC.CATEGORY_SET_NAME,
               MIC.CATEGORY_CONCAT_SEGS CATEGORIA
          FROM APPS.MTL_ITEM_CATEGORIES_V MIC, APPS.MTL_CATEGORIES_V MC
         WHERE MC.CATEGORY_ID = MIC.CATEGORY_ID
           AND MIC.CATEGORY_SET_NAME IN ('Categoria de Custo')) CUSTO_OPM,
       (SELECT MIC.INVENTORY_ITEM_ID,
               MIC.ORGANIZATION_ID,
               MIC.CATEGORY_SET_NAME,
               MIC.CATEGORY_CONCAT_SEGS CATEGORIA,
               MIC.SEGMENT3
          FROM APPS.MTL_ITEM_CATEGORIES_V MIC, APPS.MTL_CATEGORIES_V MC
         WHERE MC.CATEGORY_ID = MIC.CATEGORY_ID
           AND MIC.CATEGORY_SET_NAME IN ('Inventory')) INVENTARIO,
       (SELECT MIC.INVENTORY_ITEM_ID,
               MIC.ORGANIZATION_ID,
               MIC.CATEGORY_SET_NAME,
               MIC.CATEGORY_CONCAT_SEGS CATEGORIA
          FROM APPS.MTL_ITEM_CATEGORIES_V MIC, APPS.MTL_CATEGORIES_V MC
         WHERE MC.CATEGORY_ID = MIC.CATEGORY_ID
           AND MIC.CATEGORY_SET_NAME IN ('FISCAL_CLASSIFICATION')) FISCAL_CLASSIFICATION,
       (SELECT MIC.INVENTORY_ITEM_ID,
               MIC.ORGANIZATION_ID,
               MIC.CATEGORY_SET_NAME,
               MIC.CATEGORY_CONCAT_SEGS CATEGORIA
          FROM APPS.MTL_ITEM_CATEGORIES_V MIC, APPS.MTL_CATEGORIES_V MC
         WHERE MC.CATEGORY_ID = MIC.CATEGORY_ID
           AND MIC.CATEGORY_SET_NAME IN ('Compras')) COMPRA
--
 WHERE 1 = 1
 --AND MP.ORGANIZATION_CODE = 'ITM'
 --AND (FISCAL_CLASSIFICATION.CATEGORIA is null or
 --     FISCAL_CLASSIFICATION.CATEGORIA like '000000')
   AND pun.un_number_id        = msi.un_number_id(+)
   AND MSI.ORGANIZATION_ID     = MP.ORGANIZATION_ID
   AND MSI.ORGANIZATION_ID     = MST.ORGANIZATION_ID
   AND MSI.INVENTORY_ITEM_ID   = MST.INVENTORY_ITEM_ID
   AND MST.LANGUAGE            = 'PTB'
--   AND MSI.ITEM_TYPE NOT IN('GEQ_SERVICO','SERVICO')
   AND MSI.ORGANIZATION_ID = CUSTO_OPM.ORGANIZATION_ID(+)
   AND MSI.INVENTORY_ITEM_ID = CUSTO_OPM.INVENTORY_ITEM_ID(+)
   AND MSI.ORGANIZATION_ID = INVENTARIO.ORGANIZATION_ID(+)
   AND MSI.INVENTORY_ITEM_ID = INVENTARIO.INVENTORY_ITEM_ID(+)
   AND MSI.ORGANIZATION_ID = FISCAL_CLASSIFICATION.ORGANIZATION_ID(+)
   AND MSI.INVENTORY_ITEM_ID = FISCAL_CLASSIFICATION.INVENTORY_ITEM_ID(+)
   AND MSI.ORGANIZATION_ID = COMPRA.ORGANIZATION_ID(+)
   AND MSI.INVENTORY_ITEM_ID = COMPRA.INVENTORY_ITEM_ID(+)
   AND MSI.INVENTORY_ITEM_STATUS_CODE = 'Active'
   and msi.segment1 like '2%'
--   AND SEGMENT1 LIKE '1000%'
   --AND MSI.ITEM_TYPE NOT IN('RECURSOS_MANUTENCAO', 'GEQ_RECURSOS_MANUTENCAO','VEICULOS_OTM', 'AG', 'AA','GEQ_VEICULOS_OTM','GEQ_SERVICO','SERVICO','PH')
--   AND MP.ORGANIZATION_CODE NOT IN('E01','E02','E03','E04','C01','C02','C03','C04','C05','C06')
--   and MSI.ATTRIBUTE1 IN('5415246700')--,'4502003246')
   --AND MP.ORGANIZATION_CODE IN('057')
--   AND MSI.ATTRIBUTE19 = 'Y'
--   AND COMPRA.CATEGORIA  = '000.057.000.309' --'000.030.000.061'
-- AND CLASSE_GL_OPM.CATEGORIA IN('MERCADORIA REVENDA','PRODUTO ACABADO')
--   AND MP.ORGANIZATION_CODE IN('022','ESP','023','024','025','026','027','028','029','030','031','032')
--   AND MSI.BUYER_ID = 4279
--AND MSI.ATTRIBUTE1 IN('5810120373','7590655024','7590655083','7590655202','8600010029')
  --AND MSI.SEGMENT1 IN('1000000130')
--AND MP.ORGANIZATION_CODE IN('037','038','039','040','041','042','043','044','045','046','047','048','049','050','051','052','053','054','055','056','057','058','059','060','061','062','063','064','065','066','067','068','069','070','071','072','073','074','075','076','077','089','090','091','092','093','094','095','096','001','002','003','004','005','006','007','008','009','081','082','083','084','085','086','087','088')
--AND CLASSE_GL_OPM.CATEGORIA IN('MERCADORIA REVENDA','PRODUTO ACABADO')
--AND MSI.PRIMARY_UOM_CODE <> MSI.ATTRIBUTE18
--AND MSI.ATTRIBUTE1 = '8220002482'--IN()
--AND MSI.INVENTORY_ITEM_ID = 5226615
--AND MP.ORGANIZATION_ID = 814
--  AND MSI.ATTRIBUTE9 LIKE '%.%'
--
ORDER BY 2,3;