select ACCT_PERIOD_ID from APPS.MTL_MATERIAL_TRANSACTIONS where organization_id = 101;

SELECT MP.ORGANIZATION_CODE,
     OAP.STATUS,
     PERIOD_NAME,
     OAP.START_DATE,
     OAP.END_DATE,
     OAP.ORGANIZATION_ID,
     OAP.ACCT_PERIOD_ID

FROM APPS.ORG_ACCT_PERIODS_V OAP, APPS.MTL_PARAMETERS MP
WHERE OAP.ORGANIZATION_ID = MP.ORGANIZATION_ID
 AND PERIOD_YEAR = '2015'
 --AND PERIOD_NAME = 'abr/13'
 --AND MP.ORGANIZATION_ID = 329

ORDER BY MP.ORGANIZATION_CODE;

select segment1, primary_uom_code from apps.mtl_system_items_b where organization_id = 87;