UPDATE XXPPG_PO_CONTRATOS SET SUPPLIER_LOCAL = '0001-00';
SELECT * FROM XXPPG_PO_CONTRATOS; 
 
SELECT * FROM XXPPG_PO_CONTRATO_LINES;

SELECT * FROM xxppg_po_con_tmp;
 
SELECT * FROM xxppg_po_con_lines_tmp;

DELETE FROM XXPPG_PO_CONTRATOS; 
 
DELETE FROM XXPPG_PO_CONTRATO_LINES;

DELETE FROM xxppg_po_con_tmp;
 
DELETE FROM xxppg_po_con_lines_tmp;
