SELECT MSI.SEGMENT1                  "Item Code",
       MP.ORGANIZATION_CODE          "Organization Code",
       INVENTARIO.CATEGORIA          "Inventory Category",
       APLICACAO.CATEGORIA           "APLICACAO",
       SUB_FAM.CATEGORIA             "Sub Family",
       PROD_FAM.CATEGORIA            "Product Family",
       PRICING.CATEGORIA             "PRICING",       
       MSI.INVENTORY_ITEM_STATUS_CODE,
       msg.attribute24               "Etiq Lata",
       msg.attribute25               "Etiq Caixa"
       

  FROM APPS.MTL_SYSTEM_ITEMS MSI,
       APPS.MTL_PARAMETERS MP,
       APPS.MTL_SYSTEM_ITEMS_TL MST,
       APPS.XXPPG_PRINTER_MESSAGES msg,
       
       (SELECT MIC.INVENTORY_ITEM_ID,
               MIC.ORGANIZATION_ID,
               MIC.CATEGORY_SET_NAME,
               MIC.CATEGORY_CONCAT_SEGS CATEGORIA
          FROM APPS.MTL_ITEM_CATEGORIES_V MIC, APPS.MTL_CATEGORIES_V MC
         WHERE MC.CATEGORY_ID = MIC.CATEGORY_ID
           AND MIC.CATEGORY_SET_NAME IN ('Inventory')) INVENTARIO,
           
       (SELECT MIC.INVENTORY_ITEM_ID,
               MIC.ORGANIZATION_ID,
               MIC.CATEGORY_SET_NAME,
               MIC.CATEGORY_CONCAT_SEGS CATEGORIA
          FROM APPS.MTL_ITEM_CATEGORIES_V MIC, APPS.MTL_CATEGORIES_V MC
         WHERE MC.CATEGORY_ID = MIC.CATEGORY_ID
           AND MIC.CATEGORY_SET_NAME IN ('PPG_BR_COM_APLICACAO')) APLICACAO,
           
       (SELECT MIC.INVENTORY_ITEM_ID,
               MIC.ORGANIZATION_ID,
               MIC.CATEGORY_SET_NAME,
               MIC.CATEGORY_CONCAT_SEGS CATEGORIA
          FROM APPS.MTL_ITEM_CATEGORIES_V MIC, APPS.MTL_CATEGORIES_V MC
         WHERE MC.CATEGORY_ID = MIC.CATEGORY_ID
           AND MIC.CATEGORY_SET_NAME IN ('PPG_BR_COM_SUB_FAMILIA')) SUB_FAM,
           
       (SELECT MIC.INVENTORY_ITEM_ID,
               MIC.ORGANIZATION_ID,
               MIC.CATEGORY_SET_NAME,
               MIC.CATEGORY_CONCAT_SEGS CATEGORIA
          FROM APPS.MTL_ITEM_CATEGORIES_V MIC, APPS.MTL_CATEGORIES_V MC
         WHERE MC.CATEGORY_ID = MIC.CATEGORY_ID
           AND MIC.CATEGORY_SET_NAME IN ('PPG_BR_PRODUCT_FAMILY')) PROD_FAM,
           
       (SELECT MIC.INVENTORY_ITEM_ID,
               MIC.ORGANIZATION_ID,
               MIC.CATEGORY_SET_NAME,
               MIC.CATEGORY_CONCAT_SEGS CATEGORIA
          FROM APPS.MTL_ITEM_CATEGORIES_V MIC, APPS.MTL_CATEGORIES_V MC
         WHERE MC.CATEGORY_ID = MIC.CATEGORY_ID
           AND MIC.CATEGORY_SET_NAME IN ('Produto')) PRODUTO,
           
       (SELECT MIC.INVENTORY_ITEM_ID,
               MIC.ORGANIZATION_ID,
               MIC.CATEGORY_SET_NAME,
               MIC.CATEGORY_CONCAT_SEGS CATEGORIA
          FROM APPS.MTL_ITEM_CATEGORIES_V MIC, APPS.MTL_CATEGORIES_V MC
         WHERE MC.CATEGORY_ID = MIC.CATEGORY_ID
           AND MIC.CATEGORY_SET_NAME IN ('PPG_BR_COM_TEC_PRICING')) PRICING
           

 WHERE 1 = 1
   AND MP.ORGANIZATION_CODE <> 'ITM'
   AND MP.ORGANIZATION_CODE NOT LIKE 'T%'
   AND MSI.ORGANIZATION_ID   = MP.ORGANIZATION_ID
   AND MSI.ORGANIZATION_ID   = MST.ORGANIZATION_ID
   AND MSI.INVENTORY_ITEM_ID = MST.INVENTORY_ITEM_ID
   AND MST.LANGUAGE          = 'PTB'
   AND MSI.ORGANIZATION_ID   = INVENTARIO.ORGANIZATION_ID(+)
   AND MSI.INVENTORY_ITEM_ID = INVENTARIO.INVENTORY_ITEM_ID(+)
   
   AND message_type(+)       = 'INFORMACAO_ADICIONAL_ITEM'
   AND message_item_id(+)    = msi.inventory_item_id
   
   AND inventario.CATEGORIA LIKE 'ACA.REF%' -- Finished goods (Refinish)   
   
   
   AND MSI.ORGANIZATION_ID   = APLICACAO.ORGANIZATION_ID(+)
   AND MSI.INVENTORY_ITEM_ID = APLICACAO.INVENTORY_ITEM_ID(+)

   AND MSI.ORGANIZATION_ID   = SUB_FAM.ORGANIZATION_ID(+)
   AND MSI.INVENTORY_ITEM_ID = SUB_FAM.INVENTORY_ITEM_ID(+)

   AND MSI.ORGANIZATION_ID   = PROD_FAM.ORGANIZATION_ID(+)
   AND MSI.INVENTORY_ITEM_ID = PROD_FAM.INVENTORY_ITEM_ID(+)

   AND MSI.ORGANIZATION_ID   = PRODUTO.ORGANIZATION_ID(+)
   AND MSI.INVENTORY_ITEM_ID = PRODUTO.INVENTORY_ITEM_ID(+)

   AND MSI.ORGANIZATION_ID   = PRICING.ORGANIZATION_ID(+)
   AND MSI.INVENTORY_ITEM_ID = PRICING.INVENTORY_ITEM_ID(+)

ORDER BY 2,1;