select OLD_CATEGORY_NAME from apps.MTL_ITEM_CATEGORIES_INTERFACE;

UPDATE INV.MTL_ITEM_CATEGORIES_INTERFACE A SET PROCESS_FLAG = 1,/*SET_PROCESS_ID = 1,*/TRANSACTION_TYPE = 'UPDATE',
    OLD_CATEGORY_NAME = (SELECT MIC.CATEGORY_CONCAT_SEGS CATEGORIA
                         FROM  APPS.MTL_SYSTEM_ITEMS_B MSI,
                               APPS.MTL_ITEM_CATEGORIES_V MIC,
                               APPS.MTL_CATEGORIES_V MC,
                               APPS.MTL_PARAMETERS MP
                         WHERE MSI.ORGANIZATION_ID = MIC.ORGANIZATION_ID
                         AND   MSI.ORGANIZATION_ID = MP.ORGANIZATION_ID
                         AND   MSI.INVENTORY_ITEM_ID = MIC.INVENTORY_ITEM_ID
                         AND   MC.CATEGORY_ID = MIC.CATEGORY_ID
                         AND   MIC.CATEGORY_SET_NAME = A.CATEGORY_SET_NAME
                         AND   MP.ORGANIZATION_CODE = A.ORGANIZATION_CODE
                         AND   MSI.SEGMENT1 = A.ITEM_NUMBER)
WHERE SET_PROCESS_ID = 141;
