select segment1, inventory_item_id, organization_id from apps.mtl_system_items_b where segment1 like 'DYL02P.01%';

select segment1 
  from apps.mtl_system_items_b
 where segment1 like '%' || (select MAX(substr(segment1,10,1)) from apps.mtl_system_items_b where segment1 like 'DYL02P.01%') || '%';
 
 
SELECT * FROM LAAG_GPS_USER;
SELECT * FROM LAAG_GPS_USER_RESP;
SELECT * FROM LAAG_GPS_RESP_TABLES;
SELECT * FROM LAAG_GPS_USER_LIST;
SELECT * FROM LA_GPS_TABLES_V;
SELECT * FROM LA_GPS_RESPONSIBILITY_V;
SELECT * FROM LA_GPS_QUEUE;
SELECT * FROM AQ$_LA_GPS_QUEUE_F;
SELECT * FROM AQ$LA_GPS_QUEUE;
SELECT * FROM LAUD_LAAG_GPS_USER_V;
SELECT * FROM CSF_GPS_DEVICES;
SELECT * FROM CSF_GPS_DEVICE_ASSIGNMENTS;
SELECT * FROM CSF_GPS_LOCATION_FEEDS;
SELECT * FROM CSF_GPS_VENDORS_B;
SELECT * FROM CSF_GPS_VENDORS_TL;
SELECT * FROM CSF_GPS_VENDOR_STATUS_MAPS;
SELECT * FROM CSF_GPS_VENDORS_VL;
SELECT * FROM XXGMD_GPS_DC_TEMP;
SELECT * FROM XXGMD_GPS_FF_TEMP1;
SELECT * FROM XXGMD_GPS_LABEL_DATA;
SELECT * FROM XXGMD_GPS_PARENT_LAB;
SELECT * FROM XXGMD_GPS_CONT_TBL;
SELECT * FROM MPI_GPSI_LEGACYORDERPLI;
SELECT * FROM MPI_GPSI_LEGACYFORMSCODEXREF;
SELECT * FROM MPI_GPSI_LEGACYPRODDESCTEMP;
SELECT * FROM MPI_GPSI_LEGACYTDGSALESCODE; -- este também
SELECT * FROM MPI_GPSI_LEGACYFORMULA ORDER BY 4; --ESTE AQUI
SELECT * FROM MPI_GPSI_LEGACYCOMPOSITION;
SELECT * FROM MPI_GPSI_LEGACYORDERSLI;
SELECT * FROM MPI_GPSI_LEGACYORDERSHIPPED;
SELECT * FROM MPI_GPSI_LEGACYORDERPLACED;
SELECT * FROM MPI_GPSI_LEGACYCUSTOMERADDRESS;
SELECT * FROM MPI_GPSI_LEGACYCUSTOMERINFO;
SELECT * FROM XXGMD_GPS_NOPROCESSORG;
SELECT * FROM XXGMD_GPS_APPL_TAB_DET;
SELECT * FROM XXGMD_GPS_CHEMPROP_TAB_DET;
SELECT * FROM XXGMD_GPS_HAZ_TAB_DET;
SELECT * FROM XXGMD_GPS_OTHER_TAB_DET;
SELECT * FROM XXGMD_GPS_PROD_TAB_DET;
SELECT * FROM XXGMD_GPS_SBTITN_TAB_DET;
SELECT * FROM CSF_GPS_VENDORS_B_OBS;
SELECT * FROM CSF_GPS_VENDORS_TL_OBS;
SELECT * FROM CSF_GPS_VENDOR_STATUS_MAPS_OBS;
SELECT * FROM CSF_GPS_DEVICES_OBS;
SELECT * FROM CSF_GPS_DEVICE_ASSIGNMENTS_OBS;
SELECT * FROM CSF_GPS_LOCATION_FEEDS_OBS;
SELECT * FROM XXCMX_ONT_GPS_CONT_TBL;
SELECT * FROM XXCMX_ONT_GPS_OB_LOG_TBL;
SELECT * FROM XXCMX_ONT_GPS_ORDERS_ALL_TMP;
SELECT * FROM XXCMX_ONT_GPS_ORDERS_TMP;
SELECT * FROM XXCMX_ONT_GPS_AR_CONTACTS_V;
select * from apps.fm_form_mst               fms
where formula_id = 173738;

select * from  apps.gmd_recipes               gr where formula_id = 173738;
select * from apps.gmd_recipe_validity_rules vr where recipe_id = 214764;

select segment1,
        (SELECT NFORMULAID 
                                   FROM MPI_GPSI_LEGACYFORMULA
                                  WHERE smfgcode = msi.segment1 AND
                                        TIMESTAMP = (SELECT max(timestamp)
                                                       FROM MPI_GPSI_LEGACYFORMULA
                                                      WHERE smfgcode = msi.segment1)) formula 
  from apps.mtl_system_items_b msi
 where msi.inventory_item_id = 1347692;

select * from MPI_GPSI_LEGACYFORMULA where trunc(timestamp) = to_date('07-DEc-2018');
SELECT * FROM MPI_GPSI_LEGACYTDGSALESCODE where ssalescode like 'CA682JD%';
SELECT NFORMULAID 
  FROM MPI_GPSI_LEGACYFORMULA
 WHERE smfgcode like 'CA682JD%'; AND
       TIMESTAMP = (SELECT max(timestamp)
                      FROM MPI_GPSI_LEGACYFORMULA
                     WHERE smfgcode = 'CA682JD.45'); --ESTE AQUI
                     
                     
SELECT ROWID,SBT_PROD_CAT,SBT_SDS_FRZ,SBT_PROD_CAT_DESC,SBT_SDS_FRZ_DESC FROM XXGMD_GPS_FF_TEMP1; WHERE session_id = '2742|2021/07/08 17:18:31'                      