SELECT PHA.SEGMENT1 "ORDEM DE COMPRA"
     ,PV.SEGMENT1 FORNECEDOR
     ,PV.VENDOR_NAME "DESCRICAO FORNECEDOR"
     ,CFIL.ITEM_ID ITEM
     ,MSIB.SEGMENT1 "DESCRICAO ITEM"     
     ,CFI.INVOICE_NUM "NOTA FISCAL"
     ,PLA.UNIT_PRICE "VALOR DO ITEM ORDEM"
     ,CFIL.UNIT_PRICE "VALOR DO ITEM ENTRADA"
     ,CFI.INVOICE_DATE "DATA EMISSAO NOTA FISCAL"
     ,CFI.CREATION_DATE "DATA ENTRADA NOTA FISCAL"
     ,(select MEANING 
        from fnd_lookup_values
        where lookup_type = 'CLL_F189_CIF_FOB_FREIGHT'
        AND LANGUAGE = 'PTB'
        AND LOOKUP_CODE = CFEO.freight_flag
        AND ROWNUM = 1) "TIPO DE FRETE"
     ,FU.USER_NAME "ORDEM EMITIDA POR"
     ,(SELECT MAX(ACTION_DATE) 
        FROM PO_ACTION_HISTORY
        WHERE OBJECT_TYPE_CODE = 'PO'
        AND OBJECT_SUB_TYPE_CODE = 'STANDARD'
        AND OBJECT_ID = PHA.PO_HEADER_ID) "DATA EMISSAO PEDIDO"
 FROM CLL_F189_ENTRY_OPERATIONS CFEO
    , CLL_F189_INVOICES CFI   
    , CLL_F189_FISCAL_ENTITIES_ALL CFFEA
    , PO_VENDORS PV    
    , CLL_F189_INVOICE_LINES CFIL
    , CLL_F189_ITEM_UTILIZATIONS CFIU
    , CLL_F189_FISCAL_OPERATIONS CFFO
    , CLL_F189_INVOICE_TYPES CFIT
    , PO_LINES_ALL PLA
    , PO_LINE_LOCATIONS_ALL PLLA
    , MTL_SYSTEM_ITEMS_B MSIB
    , AP_TERMS AT
    , PO_HEADERS_ALL PHA
    , FND_USER FU
   
WHERE CFEO.ORGANIZATION_ID           = CFI.ORGANIZATION_ID
  AND CFEO.OPERATION_ID              = CFI.OPERATION_ID  
  AND CFI.ENTITY_ID                  = CFFEA.ENTITY_ID
  AND CFI.INVOICE_ID                 = CFIL.INVOICE_ID
  AND CFI.INVOICE_TYPE_ID            = CFIT.INVOICE_TYPE_ID
  AND CFI.ORGANIZATION_ID            = CFIT.ORGANIZATION_ID
  AND CFIL.UTILIZATION_ID            = CFIU.UTILIZATION_ID
  AND CFIL.CFO_ID                    = CFFO.CFO_ID  
  AND CFIL.LINE_LOCATION_ID          = PLLA.LINE_LOCATION_ID (+)
  AND PLLA.PO_LINE_ID                = PLA.PO_LINE_ID (+)
  AND PLA.PO_HEADER_ID               = PHA.PO_HEADER_ID (+)
  AND CFIL.ITEM_ID                   = MSIB.INVENTORY_ITEM_ID (+)
  AND CFIL.ORGANIZATION_ID           = MSIB.ORGANIZATION_ID (+)
  AND CFI.TERMS_ID                   = AT.TERM_ID 
  AND CFEO.CREATED_BY                = FU.USER_ID
