SELECT PAPF.PERSON_ID              
,TRUNC(PAPF.EFFECTIVE_START_DATE) "DATA INICIO EFETIVO"          
,TRUNC(PAPF.EFFECTIVE_END_DATE)   "DATA FINAL EFETIVO"         
,PAPF.BUSINESS_GROUP_ID             
,PAPF.PERSON_TYPE_ID                
,PAPF.LAST_NAME            "ULTIMO NOME"         
,PAPF.START_DATE           "DATA INICIO"         
,PAPF.APPLICANT_NUMBER              
,PAPF.BACKGROUND_CHECK_STATUS       
,PAPF.BACKGROUND_DATE_CHECK         
,PAPF.BLOOD_TYPE                    
,PAPF.COMMENT_ID                    
,PAPF.CORRESPONDENCE_LANGUAGE       
,PAPF.CURRENT_APPLICANT_FLAG        
,PAPF.CURRENT_EMP_OR_APL_FLAG       
,PAPF.CURRENT_EMPLOYEE_FLAG         
,PAPF.DATE_EMPLOYEE_DATA_VERIFIED   
,PAPF.DATE_OF_BIRTH                 
,PAPF.EMAIL_ADDRESS               
,PAPF.EMPLOYEE_NUMBER      "NUMERO EMPREGADO"         
,PAPF.EXPENSE_CHECK_SEND_TO_ADDRESS 
,PAPF.FAST_PATH_EMPLOYEE            
,PAPF.FIRST_NAME           "PRIMEIRO NOME"         
,PAPF.FTE_CAPACITY                  
,PAPF.FULL_NAME            "NOME COMPLETO"         
,PAPF.HOLD_APPLICANT_DATE_UNTIL     
,PAPF.HONORS                        
,PAPF.INTERNAL_LOCATION             
,PAPF.KNOWN_AS                      
,PAPF.LAST_MEDICAL_TEST_BY          
,PAPF.LAST_MEDICAL_TEST_DATE        
,PAPF.MAILSTOP                      
,PAPF.MARITAL_STATUS                
,PAPF.MIDDLE_NAMES                  
,PAPF.NATIONALITY                   
,PAPF.NATIONAL_IDENTIFIER           
,PAPF.OFFICE_NUMBER                 
,PAPF.ON_MILITARY_SERVICE           
,PAPF.ORDER_NAME                    
,PAPF.PRE_NAME_ADJUNCT              
,PAPF.PREVIOUS_LAST_NAME            
,PAPF.PROJECTED_START_DATE          
,PAPF.REHIRE_AUTHORIZOR             
,PAPF.REHIRE_REASON                 
,PAPF.REHIRE_RECOMMENDATION         
,PAPF.RESUME_EXISTS                 
,PAPF.RESUME_LAST_UPDATED           
,PAPF.REGISTERED_DISABLED_FLAG      
,PAPF.SECOND_PASSPORT_EXISTS        
,PAPF.SEX                           
,PAPF.STUDENT_STATUS                
,PAPF.SUFFIX                        
,PAPF.TITLE                         
,PAPF.VENDOR_ID                     
,PAPF.WORK_SCHEDULE                 
,PAPF.WORK_TELEPHONE                
,PAPF.COORD_BEN_MED_PLN_NO          
,PAPF.COORD_BEN_NO_CVG_FLAG         
,PAPF.DPDNT_ADOPTION_DATE           
,PAPF.DPDNT_VLNTRY_SVCE_FLAG        
,PAPF.RECEIPT_OF_DEATH_CERT_DATE    
,PAPF.USES_TOBACCO_FLAG             
,PAPF.BENEFIT_GROUP_ID              
,PAPF.REQUEST_ID                    
,PAPF.PROGRAM_APPLICATION_ID        
,PAPF.PROGRAM_ID                    
,PAPF.PROGRAM_UPDATE_DATE           
,PAPF.ATTRIBUTE_CATEGORY            
,PAPF.ATTRIBUTE1                    
,PAPF.ATTRIBUTE2                    
,PAPF.ATTRIBUTE3                    
,PAPF.ATTRIBUTE4                    
,PAPF.ATTRIBUTE5                    
,PAPF.ATTRIBUTE6                    
,PAPF.ATTRIBUTE7                    
,PAPF.ATTRIBUTE8                    
,PAPF.ATTRIBUTE9                    
,PAPF.ATTRIBUTE10                   
,PAPF.ATTRIBUTE11                   
,PAPF.ATTRIBUTE12                   
,PAPF.ATTRIBUTE13                   
,PAPF.ATTRIBUTE14                   
,PAPF.ATTRIBUTE15                   
,PAPF.ATTRIBUTE16                   
,PAPF.ATTRIBUTE17                   
,PAPF.ATTRIBUTE18                   
,PAPF.ATTRIBUTE19                   
,PAPF.ATTRIBUTE20                   
,PAPF.ATTRIBUTE21                   
,PAPF.ATTRIBUTE22                   
,PAPF.ATTRIBUTE23                   
,PAPF.ATTRIBUTE24                   
,PAPF.ATTRIBUTE25                   
,PAPF.ATTRIBUTE26                   
,PAPF.ATTRIBUTE27                   
,PAPF.ATTRIBUTE28                   
,PAPF.ATTRIBUTE29                   
,PAPF.ATTRIBUTE30                   
,PAPF.LAST_UPDATE_DATE              
,PAPF.LAST_UPDATED_BY               
,PAPF.LAST_UPDATE_LOGIN             
,PAPF.CREATED_BY                    
,PAPF.CREATION_DATE                 
,PAPF.PER_INFORMATION_CATEGORY      
,PAPF.PER_INFORMATION1              
,PAPF.PER_INFORMATION2              
,PAPF.PER_INFORMATION3              
,PAPF.PER_INFORMATION4              
,PAPF.PER_INFORMATION5              
,PAPF.PER_INFORMATION6              
,PAPF.PER_INFORMATION7              
,PAPF.PER_INFORMATION8              
,PAPF.PER_INFORMATION9              
,PAPF.PER_INFORMATION10             
,PAPF.PER_INFORMATION11             
,PAPF.PER_INFORMATION12             
,PAPF.PER_INFORMATION13             
,PAPF.PER_INFORMATION14             
,PAPF.PER_INFORMATION15             
,PAPF.PER_INFORMATION16             
,PAPF.PER_INFORMATION17             
,PAPF.PER_INFORMATION18             
,PAPF.PER_INFORMATION19             
,PAPF.PER_INFORMATION20             
,PAPF.PER_INFORMATION21             
,PAPF.PER_INFORMATION22             
,PAPF.PER_INFORMATION23             
,PAPF.PER_INFORMATION24             
,PAPF.PER_INFORMATION25             
,PAPF.PER_INFORMATION26             
,PAPF.PER_INFORMATION27             
,PAPF.PER_INFORMATION28             
,PAPF.PER_INFORMATION29             
,PAPF.PER_INFORMATION30             
,PAPF.OBJECT_VERSION_NUMBER         
,PAPF.DATE_OF_DEATH                 
,PAPF.ORIGINAL_DATE_OF_HIRE         
,PAPF.TOWN_OF_BIRTH                 
,PAPF.REGION_OF_BIRTH               
,PAPF.COUNTRY_OF_BIRTH              
,PAPF.GLOBAL_PERSON_ID              
,PAPF.COORD_BEN_MED_PL_NAME         
,PAPF.COORD_BEN_MED_INSR_CRR_NAME   
,PAPF.COORD_BEN_MED_INSR_CRR_IDENT  
,PAPF.COORD_BEN_MED_EXT_ER          
,PAPF.COORD_BEN_MED_CVG_STRT_DT     
,PAPF.COORD_BEN_MED_CVG_END_DT      
,PAPF.PARTY_ID                      
,PAPF.NPW_NUMBER                    
,PAPF.CURRENT_NPW_FLAG              
,PAPF.GLOBAL_NAME                   
,PAPF.LOCAL_NAME 
FROM PER_ALL_PEOPLE_F PAPF
                   
