 SELECT GR.RECIPE_NO
       ,GR.RECIPE_VERSION
       ,GR.RECIPE_DESCRIPTION
       ,GR.CREATION_ORGANIZATION_ID
       ,GR.OWNER_ORGANIZATION_ID
       ,GR.RECIPE_TYPE
       ,GR.PLANNED_PROCESS_LOSS
       ,GR.FIXED_PROCESS_LOSS
       ,GR.FIXED_PROCESS_LOSS_UOM
       ,GR.CALCULATE_STEP_QUANTITY
       ,GR.ENHANCED_PI_IND
       ,GR.CONTIGUOUS_IND
       ,GR.OWNER_LAB_TYPE
       ,GR.RECIPE_STATUS
       ,GR.FORMULA_ID
       ,GR.ROUTING_ID
       ,GR.PROJECT_ID
       ,GR.RECIPE_ID
       ,GR.TEXT_CODE
       ,GR.OWNER_ID
       ,GR.DELETE_MARK
       ,GR.CREATED_BY
       ,GR.LAST_UPDATED_BY
       ,TRUNC(GR.CREATION_DATE)
       ,GR.LAST_UPDATE_DATE
       ,GR.LAST_UPDATE_LOGIN
       ,GR.ATTRIBUTE_CATEGORY
       ,GR.ATTRIBUTE1
       ,GR.ATTRIBUTE2
       ,GR.ATTRIBUTE3
       ,GR.ATTRIBUTE4
       ,GR.ATTRIBUTE5
       ,GR.ATTRIBUTE6
       ,GR.ATTRIBUTE7
       ,GR.ATTRIBUTE8
       ,GR.ATTRIBUTE9
       ,GR.ATTRIBUTE10
       ,GR.ATTRIBUTE11
       ,GR.ATTRIBUTE12
       ,GR.ATTRIBUTE13
       ,GR.ATTRIBUTE14
       ,GR.ATTRIBUTE15
       ,GR.ATTRIBUTE16
       ,GR.ATTRIBUTE17
       ,GR.ATTRIBUTE18
       ,GR.ATTRIBUTE19
       ,GR.ATTRIBUTE20
       ,GR.ATTRIBUTE21
       ,GR.ATTRIBUTE22
       ,GR.ATTRIBUTE23
       ,GR.ATTRIBUTE24
       ,GR.ATTRIBUTE25
       ,GR.ATTRIBUTE26
       ,GR.ATTRIBUTE27
       ,GR.ATTRIBUTE28
       ,GR.ATTRIBUTE29
       ,GR.ATTRIBUTE30
       ,GRPL.PROCESS_LOSS          
       ,GRPL.RECIPE_PROCESS_LOSS_ID
       ,GRPL.ORGANIZATION_ID
       ,GRRS.ROUTINGSTEP_ID QTD_ETAPA_ROUTINGSTEP_ID
       ,GRRS.STEP_QTY       QTD_ETAPA_STEP_QTY       
       ,GRRS.TEXT_CODE      QTD_ETAPA_TEXT_CODE      
       ,GRRS.MASS_QTY       QTD_ETAPA_MASS_QTY       
       ,GRRS.MASS_REF_UOM   QTD_ETAPA_MASS_REF_UOM   
       ,GRRS.VOLUME_QTY     QTD_ETAPA_VOLUME_QTY     
       ,GRRS.VOLUME_REF_UOM QTD_ETAPA_VOLUME_REF_UOM 
       ,GRRS.ATTRIBUTE1     QTD_ETAPA_ATTRIBUTE1     
       ,GRRS.ATTRIBUTE2     QTD_ETAPA_ATTRIBUTE2     
       ,GRRS.ATTRIBUTE3     QTD_ETAPA_ATTRIBUTE3     
       ,GRRS.ATTRIBUTE4     QTD_ETAPA_ATTRIBUTE4     
       ,GRRS.ATTRIBUTE5     QTD_ETAPA_ATTRIBUTE5     
       ,GRRS.ATTRIBUTE6     QTD_ETAPA_ATTRIBUTE6     
       ,GRRS.ATTRIBUTE7     QTD_ETAPA_ATTRIBUTE7     
       ,GRRS.ATTRIBUTE8     QTD_ETAPA_ATTRIBUTE8     
       ,GRRS.ATTRIBUTE9     QTD_ETAPA_ATTRIBUTE9     
       ,GRRS.ATTRIBUTE10    QTD_ETAPA_ATTRIBUTE10    
       ,GRRS.ATTRIBUTE11    QTD_ETAPA_ATTRIBUTE11    
       ,GRRS.ATTRIBUTE12    QTD_ETAPA_ATTRIBUTE12    
       ,GRRS.ATTRIBUTE13    QTD_ETAPA_ATTRIBUTE13    
       ,GRRS.ATTRIBUTE14    QTD_ETAPA_ATTRIBUTE14    
       ,GRRS.ATTRIBUTE15    QTD_ETAPA_ATTRIBUTE15    
       ,GRRS.ATTRIBUTE16    QTD_ETAPA_ATTRIBUTE16    
       ,GRRS.ATTRIBUTE17    QTD_ETAPA_ATTRIBUTE17    
       ,GRRS.ATTRIBUTE18    QTD_ETAPA_ATTRIBUTE18    
       ,GRRS.ATTRIBUTE19    QTD_ETAPA_ATTRIBUTE19    
       ,GRRS.ATTRIBUTE20    QTD_ETAPA_ATTRIBUTE20    
       ,GRRS.ATTRIBUTE21    QTD_ETAPA_ATTRIBUTE21    
       ,GRRS.ATTRIBUTE22    QTD_ETAPA_ATTRIBUTE22    
       ,GRRS.ATTRIBUTE23    QTD_ETAPA_ATTRIBUTE23    
       ,GRRS.ATTRIBUTE24    QTD_ETAPA_ATTRIBUTE24    
       ,GRRS.ATTRIBUTE25    QTD_ETAPA_ATTRIBUTE25    
       ,GRRS.ATTRIBUTE26    QTD_ETAPA_ATTRIBUTE26    
       ,GRRS.ATTRIBUTE27    QTD_ETAPA_ATTRIBUTE27    
       ,GRRS.ATTRIBUTE28    QTD_ETAPA_ATTRIBUTE28    
       ,GRRS.ATTRIBUTE29    QTD_ETAPA_ATTRIBUTE29    
       ,GRRS.ATTRIBUTE30    QTD_ATTRIBUTE30    
       ,GRRS.MASS_STD_UOM   QTD_MASS_STD_UOM   
       ,GRRS.VOLUME_STD_UOM VOLUME_STD_UOM  
       ,GRC.CUSTOMER_ID       
       ,GRC.OPM_CUST_ID
       ,GRC.ORG_ID
       ,GRC.SITE_ID
       
       ,GRVR.RECIPE_VALIDITY_RULE_ID
       ,GRVR.INVENTORY_ITEM_ID
       ,(SELECT SEGMENT1 
          FROM MTL_SYSTEM_ITEMS_B 
         WHERE INVENTORY_ITEM_ID = GRVR.INVENTORY_ITEM_ID
           AND ORGANIZATION_ID = GRPL.ORGANIZATION_ID
           AND ROWNUM = 1) ITEM
       ,(SELECT DESCRIPTION 
          FROM MTL_SYSTEM_ITEMS_B 
         WHERE INVENTORY_ITEM_ID = GRVR.INVENTORY_ITEM_ID
           AND ORGANIZATION_ID = GRPL.ORGANIZATION_ID
           AND ROWNUM = 1) DESCRICAO_ITEM    
       ,GRVR.INV_MIN_QTY
       ,GRVR.INV_MAX_QTY       
       ,GRVR.ATTRIBUTE1     REGRA_ATTRIBUTE1
       ,GRVR.ATTRIBUTE2     REGRA_ATTRIBUTE2
       ,GRVR.ATTRIBUTE7     REGRA_ATTRIBUTE7
       ,GRVR.ATTRIBUTE8     REGRA_ATTRIBUTE8
       ,GRVR.ATTRIBUTE9     REGRA_ATTRIBUTE9
       ,GRVR.ATTRIBUTE10    REGRA_ATTRIBUTE10
       ,GRVR.ATTRIBUTE11    REGRA_ATTRIBUTE11
       ,GRVR.ATTRIBUTE12    REGRA_ATTRIBUTE12
       ,GRVR.ATTRIBUTE3     REGRA_ATTRIBUTE3
       ,GRVR.ATTRIBUTE13    REGRA_ATTRIBUTE13
       ,GRVR.ATTRIBUTE4     REGRA_ATTRIBUTE4
       ,GRVR.ATTRIBUTE14    REGRA_ATTRIBUTE14
       ,GRVR.ATTRIBUTE5     REGRA_ATTRIBUTE5
       ,GRVR.ATTRIBUTE15    REGRA_ATTRIBUTE15
       ,GRVR.ATTRIBUTE6     REGRA_ATTRIBUTE6
       ,GRVR.ATTRIBUTE16    REGRA_ATTRIBUTE16
       ,GRVR.ATTRIBUTE17    REGRA_ATTRIBUTE17
       ,GRVR.ATTRIBUTE18    REGRA_ATTRIBUTE18
       ,GRVR.ATTRIBUTE19    REGRA_ATTRIBUTE19
       ,GRVR.ATTRIBUTE20    REGRA_ATTRIBUTE20
       ,GRVR.ATTRIBUTE21    REGRA_ATTRIBUTE21
       ,GRVR.ATTRIBUTE22    REGRA_ATTRIBUTE22
       ,GRVR.ATTRIBUTE23    REGRA_ATTRIBUTE23
       ,GRVR.ATTRIBUTE24    REGRA_ATTRIBUTE24
       ,GRVR.ATTRIBUTE25    REGRA_ATTRIBUTE25
       ,GRVR.ATTRIBUTE26    REGRA_ATTRIBUTE26
       ,GRVR.ATTRIBUTE27    REGRA_ATTRIBUTE27
       ,GRVR.ATTRIBUTE28    REGRA_ATTRIBUTE28
       ,GRVR.ATTRIBUTE29    REGRA_ATTRIBUTE29
       ,GRVR.ATTRIBUTE30    REGRA_ATTRIBUTE30
       ,GRVR.RECIPE_USE    
       ,GRVR.REVISION      
       ,GRVR.PREFERENCE
       ,GRVR.STD_QTY
       ,GRVR.MIN_QTY
       ,GRVR.MAX_QTY
       ,GRVR.DETAIL_UOM       
       ,GRVR.END_DATE
       ,GRVR.START_DATE
       ,GRVR.VALIDITY_RULE_STATUS
       ,GRSM.FORMULALINE_ID       
       ,GRSM.ROUTINGSTEP_ID             
       ,GRSM.MINIMUM_TRANSFER_QTY 
       ,GRSM.MINIMUM_DELAY        
       ,GRSM.MAXIMUM_DELAY        
       ,GRSM.ATTRIBUTE1     GRSM_ATTRIBUTE1       
       ,GRSM.ATTRIBUTE2     GRSM_ATTRIBUTE2       
       ,GRSM.ATTRIBUTE3     GRSM_ATTRIBUTE3       
       ,GRSM.ATTRIBUTE4     GRSM_ATTRIBUTE4       
       ,GRSM.ATTRIBUTE5     GRSM_ATTRIBUTE5       
       ,GRSM.ATTRIBUTE6     GRSM_ATTRIBUTE6       
       ,GRSM.ATTRIBUTE7     GRSM_ATTRIBUTE7       
       ,GRSM.ATTRIBUTE8     GRSM_ATTRIBUTE8       
       ,GRSM.ATTRIBUTE9     GRSM_ATTRIBUTE9       
       ,GRSM.ATTRIBUTE10    GRSM_ATTRIBUTE10      
       ,GRSM.ATTRIBUTE11    GRSM_ATTRIBUTE11      
       ,GRSM.ATTRIBUTE12    GRSM_ATTRIBUTE12      
       ,GRSM.ATTRIBUTE13    GRSM_ATTRIBUTE13      
       ,GRSM.ATTRIBUTE14    GRSM_ATTRIBUTE14      
       ,GRSM.ATTRIBUTE15    GRSM_ATTRIBUTE15      
       ,GRSM.ATTRIBUTE16    GRSM_ATTRIBUTE16      
       ,GRSM.ATTRIBUTE17    GRSM_ATTRIBUTE17      
       ,GRSM.ATTRIBUTE18    GRSM_ATTRIBUTE18      
       ,GRSM.ATTRIBUTE19    GRSM_ATTRIBUTE19      
       ,GRSM.ATTRIBUTE20    GRSM_ATTRIBUTE20      
       ,GRSM.ATTRIBUTE21    GRSM_ATTRIBUTE21      
       ,GRSM.ATTRIBUTE22    GRSM_ATTRIBUTE22      
       ,GRSM.ATTRIBUTE23    GRSM_ATTRIBUTE23      
       ,GRSM.ATTRIBUTE24    GRSM_ATTRIBUTE24      
       ,GRSM.ATTRIBUTE25    GRSM_ATTRIBUTE25      
       ,GRSM.ATTRIBUTE26    GRSM_ATTRIBUTE26      
       ,GRSM.ATTRIBUTE27    GRSM_ATTRIBUTE27      
       ,GRSM.ATTRIBUTE28    GRSM_ATTRIBUTE28      
       ,GRSM.ATTRIBUTE29    GRSM_ATTRIBUTE29      
       ,GRSM.ATTRIBUTE30    GRSM_ATTRIBUTE30               
       ,FFM.FORMULA_DESC1         
       ,FFM.FORMULA_DESC2         
       ,FFM.FORMULA_NO            
       ,FFM.FORMULA_VERS          
       ,FFM.FORMULA_TYPE          
       ,FFM.SCALE_TYPE            
       ,FFM.FORMULA_CLASS         
       ,FFM.FMCONTROL_CLASS       
       ,FFM.IN_USE                
       ,FFM.INACTIVE_IND          
       ,FFM.ATTRIBUTE1       FFM_ATTRIBUTE1      
       ,FFM.ATTRIBUTE2       FFM_ATTRIBUTE2      
       ,FFM.ATTRIBUTE3       FFM_ATTRIBUTE3      
       ,FFM.ATTRIBUTE4       FFM_ATTRIBUTE4      
       ,FFM.ATTRIBUTE5       FFM_ATTRIBUTE5      
       ,FFM.ATTRIBUTE6       FFM_ATTRIBUTE6      
       ,FFM.ATTRIBUTE7       FFM_ATTRIBUTE7      
       ,FFM.ATTRIBUTE8       FFM_ATTRIBUTE8      
       ,FFM.ATTRIBUTE9       FFM_ATTRIBUTE9      
       ,FFM.ATTRIBUTE10      FFM_ATTRIBUTE10     
       ,FFM.ATTRIBUTE11      FFM_ATTRIBUTE11     
       ,FFM.ATTRIBUTE12      FFM_ATTRIBUTE12     
       ,FFM.ATTRIBUTE13      FFM_ATTRIBUTE13     
       ,FFM.ATTRIBUTE14      FFM_ATTRIBUTE14     
       ,FFM.ATTRIBUTE15      FFM_ATTRIBUTE15     
       ,FFM.ATTRIBUTE16      FFM_ATTRIBUTE16     
       ,FFM.ATTRIBUTE17      FFM_ATTRIBUTE17     
       ,FFM.ATTRIBUTE18      FFM_ATTRIBUTE18     
       ,FFM.ATTRIBUTE19      FFM_ATTRIBUTE19     
       ,FFM.ATTRIBUTE20      FFM_ATTRIBUTE20     
       ,FFM.ATTRIBUTE21      FFM_ATTRIBUTE21     
       ,FFM.ATTRIBUTE22      FFM_ATTRIBUTE22     
       ,FFM.ATTRIBUTE23      FFM_ATTRIBUTE23     
       ,FFM.ATTRIBUTE24      FFM_ATTRIBUTE24     
       ,FFM.ATTRIBUTE25      FFM_ATTRIBUTE25     
       ,FFM.ATTRIBUTE26      FFM_ATTRIBUTE26     
       ,FFM.ATTRIBUTE27      FFM_ATTRIBUTE27     
       ,FFM.ATTRIBUTE28      FFM_ATTRIBUTE28     
       ,FFM.ATTRIBUTE29      FFM_ATTRIBUTE29     
       ,FFM.ATTRIBUTE30      FFM_ATTRIBUTE30                                            
       ,FFM.FORMULA_STATUS                             
       ,FFM.TOTAL_INPUT_QTY       
       ,FFM.TOTAL_OUTPUT_QTY      
       ,FFM.YIELD_UOM             
       ,FFM.MASTER_FORMULA_ID     
       ,FFM.AUTO_PRODUCT_CALC           
       ,FMD.LINE_TYPE               
       ,FMD.LINE_NO                 
       ,FMD.ITEM_ID                 
       ,FMD.QTY                     
       ,FMD.ITEM_UM                 
       ,FMD.RELEASE_TYPE            
       ,FMD.SCRAP_FACTOR                      
       ,FMD.COST_ALLOC              
       ,FMD.PHANTOM_TYPE            
       ,FMD.REWORK_TYPE             
       ,FMD.ATTRIBUTE1    FMD_ATTRIBUTE1           
       ,FMD.ATTRIBUTE2    FMD_ATTRIBUTE2           
       ,FMD.ATTRIBUTE3    FMD_ATTRIBUTE3           
       ,FMD.ATTRIBUTE4    FMD_ATTRIBUTE4           
       ,FMD.ATTRIBUTE5    FMD_ATTRIBUTE5           
       ,FMD.ATTRIBUTE6    FMD_ATTRIBUTE6           
       ,FMD.ATTRIBUTE7    FMD_ATTRIBUTE7           
       ,FMD.ATTRIBUTE8    FMD_ATTRIBUTE8           
       ,FMD.ATTRIBUTE9    FMD_ATTRIBUTE9           
       ,FMD.ATTRIBUTE10   FMD_ATTRIBUTE10          
       ,FMD.ATTRIBUTE11   FMD_ATTRIBUTE11          
       ,FMD.ATTRIBUTE12   FMD_ATTRIBUTE12          
       ,FMD.ATTRIBUTE13   FMD_ATTRIBUTE13          
       ,FMD.ATTRIBUTE14   FMD_ATTRIBUTE14          
       ,FMD.ATTRIBUTE15   FMD_ATTRIBUTE15          
       ,FMD.ATTRIBUTE16   FMD_ATTRIBUTE16          
       ,FMD.ATTRIBUTE17   FMD_ATTRIBUTE17          
       ,FMD.ATTRIBUTE18   FMD_ATTRIBUTE18          
       ,FMD.ATTRIBUTE19   FMD_ATTRIBUTE19          
       ,FMD.ATTRIBUTE20   FMD_ATTRIBUTE20          
       ,FMD.ATTRIBUTE21   FMD_ATTRIBUTE21          
       ,FMD.ATTRIBUTE22   FMD_ATTRIBUTE22          
       ,FMD.ATTRIBUTE23   FMD_ATTRIBUTE23          
       ,FMD.ATTRIBUTE24   FMD_ATTRIBUTE24          
       ,FMD.ATTRIBUTE25   FMD_ATTRIBUTE25          
       ,FMD.ATTRIBUTE26   FMD_ATTRIBUTE26          
       ,FMD.ATTRIBUTE27   FMD_ATTRIBUTE27          
       ,FMD.ATTRIBUTE28   FMD_ATTRIBUTE28          
       ,FMD.ATTRIBUTE29   FMD_ATTRIBUTE29          
       ,FMD.ATTRIBUTE30   FMD_ATTRIBUTE30          
       ,FMD.TPFORMULA_ID            
       ,FMD.IAFORMULA_ID            
       ,FMD.SCALE_UOM               
       ,FMD.CONTRIBUTE_STEP_QTY_IND 
       ,FMD.CONTRIBUTE_YIELD_IND    
       ,FMD.SCALE_MULTIPLE          
       ,FMD.SCALE_ROUNDING_VARIANCE 
       ,FMD.ROUNDING_DIRECTION      
       ,FMD.BY_PRODUCT_TYPE         
       ,FMD.BUFFER_IND              
       ,(SELECT SEGMENT1 
          FROM MTL_SYSTEM_ITEMS_B 
         WHERE INVENTORY_ITEM_ID = FMD.INVENTORY_ITEM_ID
           AND ORGANIZATION_ID = GRPL.ORGANIZATION_ID
           AND ROWNUM = 1) ITEM_LINHA
       ,(SELECT DESCRIPTION 
          FROM MTL_SYSTEM_ITEMS_B 
         WHERE INVENTORY_ITEM_ID = FMD.INVENTORY_ITEM_ID
           AND ORGANIZATION_ID = GRPL.ORGANIZATION_ID
           AND ROWNUM = 1) DESCRICAO_ITEM_LINHA                                           
       ,FMD.INGREDIENT_END_DATE     
       ,FMD.PROD_PERCENT       
       ,FRH.ROUTING_NO
       ,FRH.ROUTING_VERS
       ,FRH.ROUTING_DESC
       ,FRH.ROUTING_CLASS   
       ,FRH.ROUTING_QTY
       ,FRH.ROUTING_UOM     
       ,FRH.ROUTING_STATUS  
       ,FRH.ATTRIBUTE1     ROT_ATTRIBUTE1
       ,FRH.ATTRIBUTE2     ROT_ATTRIBUTE2
       ,FRH.ATTRIBUTE3     ROT_ATTRIBUTE3
       ,FRH.ATTRIBUTE4     ROT_ATTRIBUTE4
       ,FRH.ATTRIBUTE5     ROT_ATTRIBUTE5
       ,FRH.ATTRIBUTE6     ROT_ATTRIBUTE6
       ,FRH.ATTRIBUTE7     ROT_ATTRIBUTE7
       ,FRH.ATTRIBUTE8     ROT_ATTRIBUTE8
       ,FRH.ATTRIBUTE9     ROT_ATTRIBUTE9
       ,FRH.ATTRIBUTE10    ROT_ATTRIBUTE10
       ,FRH.ATTRIBUTE11    ROT_ATTRIBUTE11
       ,FRH.ATTRIBUTE12    ROT_ATTRIBUTE12
       ,FRH.ATTRIBUTE13    ROT_ATTRIBUTE13
       ,FRH.ATTRIBUTE14    ROT_ATTRIBUTE14
       ,FRH.ATTRIBUTE15    ROT_ATTRIBUTE15
       ,FRH.ATTRIBUTE16    ROT_ATTRIBUTE16
       ,FRH.ATTRIBUTE17    ROT_ATTRIBUTE17
       ,FRH.ATTRIBUTE18    ROT_ATTRIBUTE18
       ,FRH.ATTRIBUTE19    ROT_ATTRIBUTE19
       ,FRH.ATTRIBUTE20    ROT_ATTRIBUTE20
       ,FRH.ATTRIBUTE21    ROT_ATTRIBUTE21
       ,FRH.ATTRIBUTE22    ROT_ATTRIBUTE22
       ,FRH.ATTRIBUTE23    ROT_ATTRIBUTE23
       ,FRH.ATTRIBUTE24    ROT_ATTRIBUTE24
       ,FRH.ATTRIBUTE25    ROT_ATTRIBUTE25
       ,FRH.ATTRIBUTE26    ROT_ATTRIBUTE26
       ,FRH.ATTRIBUTE27    ROT_ATTRIBUTE27
       ,FRH.ATTRIBUTE28    ROT_ATTRIBUTE28
       ,FRH.ATTRIBUTE29    ROT_ATTRIBUTE29
       ,FRH.ATTRIBUTE30    ROT_ATTRIBUTE30
       ,FRD.ROUTINGSTEP_NO  
       ,FRD.STEPRELEASE_TYPE
       ,FRD.OPRN_ID         
       ,FRD.ATTRIBUTE1     FRD_ATTRIBUTE1
       ,FRD.ATTRIBUTE2     FRD_ATTRIBUTE2
       ,FRD.ATTRIBUTE3     FRD_ATTRIBUTE3
       ,FRD.ATTRIBUTE4     FRD_ATTRIBUTE4
       ,FRD.ATTRIBUTE5     FRD_ATTRIBUTE5
       ,FRD.ATTRIBUTE6     FRD_ATTRIBUTE6
       ,FRD.ATTRIBUTE7     FRD_ATTRIBUTE7
       ,FRD.ATTRIBUTE8     FRD_ATTRIBUTE8
       ,FRD.ATTRIBUTE9     FRD_ATTRIBUTE9
       ,FRD.ATTRIBUTE10    FRD_ATTRIBUTE10
       ,FRD.ATTRIBUTE11    FRD_ATTRIBUTE11
       ,FRD.ATTRIBUTE12    FRD_ATTRIBUTE12
       ,FRD.ATTRIBUTE13    FRD_ATTRIBUTE13
       ,FRD.ATTRIBUTE14    FRD_ATTRIBUTE14
       ,FRD.ATTRIBUTE15    FRD_ATTRIBUTE15
       ,FRD.ATTRIBUTE16    FRD_ATTRIBUTE16
       ,FRD.ATTRIBUTE17    FRD_ATTRIBUTE17
       ,FRD.ATTRIBUTE18    FRD_ATTRIBUTE18
       ,FRD.ATTRIBUTE19    FRD_ATTRIBUTE19
       ,FRD.ATTRIBUTE20    FRD_ATTRIBUTE20
       ,FRD.ATTRIBUTE21    FRD_ATTRIBUTE21
       ,FRD.ATTRIBUTE22    FRD_ATTRIBUTE22
       ,FRD.ATTRIBUTE23    FRD_ATTRIBUTE23
       ,FRD.ATTRIBUTE24    FRD_ATTRIBUTE24
       ,FRD.ATTRIBUTE25    FRD_ATTRIBUTE25
       ,FRD.ATTRIBUTE26    FRD_ATTRIBUTE26
       ,FRD.ATTRIBUTE27    FRD_ATTRIBUTE27
       ,FRD.ATTRIBUTE28    FRD_ATTRIBUTE28
       ,FRD.ATTRIBUTE29    FRD_ATTRIBUTE29
       ,FRD.ATTRIBUTE30    FRD_ATTRIBUTE30     
       ,GOV.OPRN_NO
       ,GOV.OPRN_VERS
       ,GOV.OPRN_DESC
       ,GOV.OPRN_CLASS     
       ,GOV.PROCESS_QTY_UOM   
       ,GOA.ACTIVITY
       ,GOA.ACTIVITY_FACTOR
       ,GOA.OFFSET_INTERVAL
       ,GOA.SEQUENCE_DEPENDENT_IND
       ,GOA.BREAK_IND
       ,GOA.MAX_BREAK
       ,GOA.MATERIAL_IND
       ,GOA.OPRN_LINE_ID      
       ,GOR.RESOURCES
       ,GOR.PROCESS_QTY
       ,GOR.RESOURCE_PROCESS_UOM
       ,GOR.RESOURCE_USAGE
       ,GOR.RESOURCE_USAGE_UOM
       ,GOR.COST_ANALYSIS_CODE
       ,GOR.PRIM_RSRC_IND
       ,GOR.RESOURCE_COUNT
       ,GOR.PROCESS_PARAMETER_1
       ,GOR.PROCESS_PARAMETER_2
       ,GOR.PROCESS_PARAMETER_3
       ,GOR.PROCESS_PARAMETER_4
       ,GOR.PROCESS_PARAMETER_5 
       ,GOR.COST_CMPNTCLS_ID                  
  FROM GMD_RECIPES GR      
      ,GMD_RECIPE_PROCESS_LOSS GRPL
      ,GMD_RECIPE_ROUTING_STEPS GRRS
      ,GMD_RECIPE_CUSTOMERS GRC
      ,GMD_RECIPE_VALIDITY_RULES GRVR
      ,GMD_RECIPE_STEP_MATERIALS GRSM
      ,FM_FORM_MST FFM     
      ,FM_MATL_DTL FMD
      ,FM_ROUT_HDR FRH
      ,FM_ROUT_DTL FRD
      ,GMD_OPERATIONS_VL GOV  
      ,GMD_OPERATION_ACTIVITIES GOA     
      ,GMD_OPERATION_RESOURCES GOR
 WHERE GR.RECIPE_ID = GRPL.RECIPE_ID (+)
   AND GR.RECIPE_ID = GRRS.RECIPE_ID (+)
   AND GR.RECIPE_ID = GRC.RECIPE_ID (+)
   AND GR.RECIPE_ID = GRVR.RECIPE_ID (+)
   AND GR.RECIPE_ID = GRSM.RECIPE_ID (+)
   AND GR.FORMULA_ID = FFM.FORMULA_ID   
   AND FMD.FORMULALINE_ID = GRSM.FORMULALINE_ID
   AND FMD.FORMULA_ID = FFM.FORMULA_ID   
   AND GR.ROUTING_ID = FRH.ROUTING_ID
   AND FRH.ROUTING_ID = FRD.ROUTING_ID   
   AND GRSM.ROUTINGSTEP_ID = FRD.ROUTINGSTEP_ID 
   AND GOV.OPRN_ID = FRD.OPRN_ID 
   AND GOV.OPRN_ID = GOA.OPRN_ID
   AND GOR.OPRN_LINE_ID = GOA.OPRN_LINE_ID    