SELECT GS.SPEC_ID
       ,GS.SPEC_NAME
       ,GS.SPEC_VERS
       ,GS.SPEC_STATUS
       ,GS.SPEC_DESC
       ,GS.SPEC_TYPE
       ,GS.OVERLAY_IND
       ,GS.BASE_SPEC_ID
       ,GS.REVISION
       ,GS.GRADE_CODE
       ,GS.OWNER_ID
       ,GS.SAMPLE_INV_TRANS_IND
       ,GS.DELETE_MARK
       ,GS.TEXT_CODE
       ,GS.ATTRIBUTE_CATEGORY
       ,GS.ATTRIBUTE1
       ,GS.ATTRIBUTE2
       ,GS.ATTRIBUTE3
       ,GS.ATTRIBUTE4
       ,GS.ATTRIBUTE5
       ,GS.ATTRIBUTE6
       ,GS.ATTRIBUTE7
       ,GS.ATTRIBUTE8
       ,GS.ATTRIBUTE9
       ,GS.ATTRIBUTE10
       ,GS.ATTRIBUTE11
       ,GS.ATTRIBUTE12
       ,GS.ATTRIBUTE13
       ,GS.ATTRIBUTE14
       ,GS.ATTRIBUTE15
       ,GS.ATTRIBUTE16
       ,GS.ATTRIBUTE17
       ,GS.ATTRIBUTE18
       ,GS.ATTRIBUTE19
       ,GS.ATTRIBUTE20
       ,GS.ATTRIBUTE21
       ,GS.ATTRIBUTE22
       ,GS.ATTRIBUTE23
       ,GS.ATTRIBUTE24
       ,GS.ATTRIBUTE25
       ,GS.ATTRIBUTE26
       ,GS.ATTRIBUTE27
       ,GS.ATTRIBUTE28
       ,GS.ATTRIBUTE29
       ,GS.ATTRIBUTE30
       ,GS.CREATION_DATE
       ,GS.CREATED_BY
       ,GS.LAST_UPDATED_BY
       ,GS.LAST_UPDATE_DATE
       ,GS.LAST_UPDATE_LOGIN
       ,GS.INVENTORY_ITEM_ID
       ,GS.OWNER_ORGANIZATION_ID
       ,GST.TEST_ID
       ,(SELECT TEST_CODE 
       FROM GMD.GMD_QC_TESTS_B
       WHERE TEST_ID = GST.TEST_ID
       AND ROWNUM = 1) TEST_CODE
       ,GST.TEST_METHOD_ID
       ,(SELECT TEST_METHOD_CODE 
          FROM GMD.GMD_TEST_METHODS_B
          WHERE TEST_METHOD_ID = GST.TEST_METHOD_ID
          AND ROWNUM = 1) TEST_METHOD_DESC
       ,GST.SEQ
       ,GST.FROM_BASE_IND
       ,GST.EXCLUDE_IND
       ,GST.MODIFIED_IND
       ,GST.TEST_QTY
       ,GST.TEST_QTY_UOM
       ,GST.MIN_VALUE_NUM
       ,GST.TARGET_VALUE_NUM
       ,GST.MAX_VALUE_NUM
       ,GST.MIN_VALUE_CHAR
       ,GST.TARGET_VALUE_CHAR
       ,GST.MAX_VALUE_CHAR
       ,GST.TEST_REPLICATE
       ,GST.TEST_PRIORITY
       ,GST.OPTIONAL_IND
       ,GST.RETEST_LOT_EXPIRY_IND
       ,GST.OUT_OF_SPEC_ACTION
       ,GST.CHECK_RESULT_INTERVAL
       ,GST.CALC_UOM_CONV_IND
       ,GST.TO_QTY_UOM
       ,GST.EXP_ERROR_TYPE
       ,GST.BELOW_SPEC_MIN
       ,GST.BELOW_MIN_ACTION_CODE
       ,GST.ABOVE_SPEC_MIN
       ,GST.ABOVE_MIN_ACTION_CODE
       ,GST.BELOW_SPEC_MAX
       ,GST.BELOW_MAX_ACTION_CODE
       ,GST.ABOVE_SPEC_MAX
       ,GST.ABOVE_MAX_ACTION_CODE
       ,GST.TEST_DISPLAY
       ,GST.PRINT_SPEC_IND
       ,GST.PRINT_RESULT_IND
       ,GST.DISPLAY_PRECISION
       ,GST.REPORT_PRECISION      
       ,GST.DAYS
       ,GST.HOURS
       ,GST.MINUTES
       ,GST.SECONDS
       ,GST.VIABILITY_DURATION
       ,GST.ATTRIBUTE1    GST_ATTRIBUTE1
       ,GST.ATTRIBUTE2    GST_ATTRIBUTE2
       ,GST.ATTRIBUTE3    GST_ATTRIBUTE3
       ,GST.ATTRIBUTE4    GST_ATTRIBUTE4
       ,GST.ATTRIBUTE5    GST_ATTRIBUTE5
       ,GST.ATTRIBUTE6    GST_ATTRIBUTE6
       ,GST.ATTRIBUTE7    GST_ATTRIBUTE7
       ,GST.ATTRIBUTE8    GST_ATTRIBUTE8
       ,GST.ATTRIBUTE9    GST_ATTRIBUTE9
       ,GST.ATTRIBUTE10   GST_ATTRIBUTE10
       ,GST.ATTRIBUTE11   GST_ATTRIBUTE11
       ,GST.ATTRIBUTE12   GST_ATTRIBUTE12
       ,GST.ATTRIBUTE13   GST_ATTRIBUTE13
       ,GST.ATTRIBUTE14   GST_ATTRIBUTE14
       ,GST.ATTRIBUTE15   GST_ATTRIBUTE15
       ,GST.ATTRIBUTE16   GST_ATTRIBUTE16
       ,GST.ATTRIBUTE17   GST_ATTRIBUTE17
       ,GST.ATTRIBUTE18   GST_ATTRIBUTE18
       ,GST.ATTRIBUTE19   GST_ATTRIBUTE19
       ,GST.ATTRIBUTE20   GST_ATTRIBUTE20
       ,GST.ATTRIBUTE21   GST_ATTRIBUTE21
       ,GST.ATTRIBUTE22   GST_ATTRIBUTE22
       ,GST.ATTRIBUTE23   GST_ATTRIBUTE23
       ,GST.ATTRIBUTE24   GST_ATTRIBUTE24
       ,GST.ATTRIBUTE25   GST_ATTRIBUTE25
       ,GST.ATTRIBUTE26   GST_ATTRIBUTE26
       ,GST.ATTRIBUTE27   GST_ATTRIBUTE27
       ,GST.ATTRIBUTE28   GST_ATTRIBUTE28
       ,GST.ATTRIBUTE29   GST_ATTRIBUTE29
       ,GST.ATTRIBUTE30   GST_ATTRIBUTE30
       ,GASVV.SPEC_VR_ID       
       ,GASVV.ORGANIZATION_ID
       ,GASVV.ORGANIZATION_CODE       
       ,GASVV.SPEC_VR_STATUS
       ,GASVV.SPEC_VR_STATUS_DESC
       ,GASVV.START_DATE
       ,GASVV.END_DATE
       ,GASVV.PARENT_LOT_NUMBER
       ,GASVV.LOT_NUMBER
       ,GASVV.SUBINVENTORY
       ,GASVV.LOCATOR_ID
       ,GASVV.LOCATOR
       ,GASVV.SAMPLING_PLAN_ID       
       ,GASVV.CONTROL_LOT_ATTRIB_IND
       ,GASVV.OUT_OF_SPEC_LOT_STATUS_ID
       ,GASVV.IN_SPEC_LOT_STATUS_ID
       ,GASVV.CONTROL_BATCH_STEP_IND
       ,GASVV.LOT_OPTIONAL_ON_SAMPLE
       ,GASVV.DELAYED_LOT_ENTRY
       ,GASVV.DELAYED_LPN_ENTRY
       ,GASVV.COA_TYPE
       ,GASVV.COA_AT_SHIP_IND
       ,GASVV.COA_AT_INVOICE_IND
       ,GASVV.COA_REQ_FROM_SUPL_IND
       ,GASVV.BATCH_ID
       ,GASVV.RECIPE_ID
       ,GASVV.RECIPE_NO
       ,GASVV.RECIPE_VERSION
       ,GASVV.FORMULA_ID
       ,GASVV.FORMULALINE_ID
       ,GASVV.FORMULA_NO
       ,GASVV.FORMULA_VERS
       ,GASVV.ROUTING_ID
       ,GASVV.ROUTING_NO
       ,GASVV.ROUTING_VERS
       ,GASVV.STEP_ID
       ,GASVV.OPRN_ID
       ,GASVV.OPRN_NO
       ,GASVV.OPRN_VERS
       ,GASVV.CHARGE
       ,GASVV.CUST_ID
       ,GASVV.ORDER_ID
       ,GASVV.ORDER_LINE
       ,GASVV.ORDER_LINE_ID
       ,GASVV.SHIP_TO_SITE_ID
       ,GASVV.ORG_ID
       ,GASVV.SUPPLIER_ID
       ,GASVV.SUPPLIER_SITE_ID
       ,GASVV.PO_HEADER_ID
       ,GASVV.PO_LINE_ID          
  FROM APPS.GMD_SPECIFICATIONS_VL GS
      ,APPS.GMD_SPEC_TESTS_VL GST
      ,APPS.GMD_ALL_SPEC_VRS_VL GASVV
 WHERE GS.SPEC_ID = GST.SPEC_ID     
   AND GS.SPEC_ID = GASVV.SPEC_ID