SELECT   DISTINCT FALRI.request_id, FALRI.COST_CENTER, gcc.segment5
        ,FALRI.BOOK_TYPE_CODE
        ,FALRI.SET_OF_BOOKS_ID
        ,FALRI.PERIOD_NAME
        ,FALRI.COMPANY_DESCRIPTION
        ,FALRI.ORGANIZATION_NAME
        ,FALRI.COMPANY
        ,FALRI.ASSET_NUMBER
        ,FALRI.TAG_NUMBER
        ,FALRI.DESCRIPTION
        ,FALRI.SERIAL_NUMBER
        ,FALRI.ASSET_COST_ACCT
        ,FALRI.ACCOUNT_DESCRIPTION
        ,FALRI.DEPRN_EXPENSE_ACCT
        ,FALRI.EXPENSE_ACCT_DESCRIPTION
        ,FALRI.ACCUM_DEPRN_ACCT
        ,FALRI.CATEGORY
        ,FALRI.MAJOR_CATEGORY
        ,FALRI.MINOR_CATEGORY
        ,GCC.CONCATENATED_SEGMENTS
        ,FALRI.LOCATION 
        ,FALRI.DATE_PLACED_IN_SERVICE
        ,FDH.UNITS_ASSIGNED
        ,FALRI.s_cost * (FDH.UNITS_ASSIGNED/S_UNITS) COST
        ,FALRI.s_deprn_amount * (FDH.UNITS_ASSIGNED/S_UNITS) DEPRN_AMOUNT
        ,FALRI.s_ltd_deprn * (FDH.UNITS_ASSIGNED/S_UNITS) LTD_DEPRN
        ,FALRI.s_nbv * (FDH.UNITS_ASSIGNED/S_UNITS) NBV
        ,FALRI.DEPRN_METHOD
        ,FALRI.LIFE_YR_MO
        ,FALRI.BOOK_DEPRN_FLAG
        ,FALRI.CATEGORY_DEPRN_FLAG
        ,FALRI.ASSET_KEY 
  FROM APPS.FA_DISTRIBUTION_HISTORY FDH,
       APPS.GL_CODE_COMBINATIONS_KFV GCC,
       apps.fa_locations fl,
       apps.fa_additions_b faa,
       APPS.FA_DEPRN_PERIODS FDP,(
   SELECT FALRI.BOOK_TYPE_CODE
        ,falri.request_id
        ,FALRI.SET_OF_BOOKS_ID
        ,FALRI.PERIOD_NAME
        ,FALRI.COMPANY_DESCRIPTION
        ,FALRI.ORGANIZATION_NAME
        ,FALRI.COMPANY
        ,FALRI.ASSET_NUMBER
        ,FALRI.TAG_NUMBER
        ,FALRI.DESCRIPTION
        ,FALRI.SERIAL_NUMBER
        ,FALRI.ASSET_COST_ACCT
        ,FALRI.ACCOUNT_DESCRIPTION
        ,FALRI.DEPRN_EXPENSE_ACCT
        ,FALRI.EXPENSE_ACCT_DESCRIPTION
        ,FALRI.ACCUM_DEPRN_ACCT
        ,FALRI.CATEGORY
        ,FALRI.MAJOR_CATEGORY
        ,FALRI.MINOR_CATEGORY
        ,FALRI.LOCATION 
        ,FALRI.DATE_PLACED_IN_SERVICE
        ,FALRI.DEPRN_METHOD
        ,FALRI.LIFE_YR_MO
        ,FALRI.BOOK_DEPRN_FLAG
        ,FALRI.CATEGORY_DEPRN_FLAG
        ,FALRI.ASSET_KEY
        ,FALRI.COST_CENTER
        ,SUM(decode (FALRI.ASSET_NUMBER, '133320', 1, FALRI.UNITS)) S_UNITS 
        ,SUM(FALRI.COST) s_cost
        ,SUM(FALRI.DEPRN_AMOUNT) s_deprn_amount
        ,SUM(FALRI.LTD_DEPRN) s_ltd_deprn
        ,SUM(FALRI.NBV) s_nbv
   FROM APPS.FA_ASSET_LISTING_REP_ITF FALRI
   WHERE 1 = 1 
        AND FALRI.REQUEST_ID = (SELECT MAX(REQUEST_ID) 
                                  FROM APPS.FND_CONC_REQ_SUMMARY_V                  
                                 WHERE CONCURRENT_PROGRAM_ID = 39749
                                  AND PROGRAM_SHORT_NAME = 'RXFAAL')
     GROUP BY FALRI.REQUEST_ID
        ,FALRI.BOOK_TYPE_CODE
        ,FALRI.SET_OF_BOOKS_ID
        ,FALRI.PERIOD_NAME
        ,FALRI.COMPANY_DESCRIPTION
        ,FALRI.ORGANIZATION_NAME
        ,FALRI.COMPANY
        ,FALRI.ASSET_NUMBER
        ,FALRI.TAG_NUMBER
        ,FALRI.DESCRIPTION
        ,FALRI.SERIAL_NUMBER
        ,FALRI.ASSET_COST_ACCT
        ,FALRI.ACCOUNT_DESCRIPTION
        ,FALRI.DEPRN_EXPENSE_ACCT
        ,FALRI.EXPENSE_ACCT_DESCRIPTION
        ,FALRI.ACCUM_DEPRN_ACCT
        ,FALRI.CATEGORY
        ,FALRI.MAJOR_CATEGORY
        ,FALRI.MINOR_CATEGORY
        ,FALRI.LOCATION 
        ,FALRI.DATE_PLACED_IN_SERVICE
        ,FALRI.DEPRN_METHOD
        ,FALRI.LIFE_YR_MO
        ,FALRI.BOOK_DEPRN_FLAG
        ,FALRI.CATEGORY_DEPRN_FLAG
        ,FALRI.ASSET_KEY
        ,FALRI.COST_CENTER
       ) FALRI
WHERE 1 = 1 
    AND GCC.CODE_COMBINATION_ID = FDH.CODE_COMBINATION_ID 
    and faa.asset_number = FALRI.ASSET_NUMBER
    and faa.asset_id = FDH.ASSET_ID
    and FALRI.PERIOD_NAME = fdp.period_name
    and fdh.BOOK_TYPE_CODE = fdp.BOOK_TYPE_CODE
    and fdh.DATE_EFFECTIVE <= fdp.PERIOD_CLOSE_DATE
    and nvl(date_ineffective,fdp.PERIOD_CLOSE_DATE) >=  fdp.PERIOD_CLOSE_DATE
    and fdh.location_id = fl.location_id 
    and fl.segment1||'-'||fl.segment2||'-'||fl.segment3 = FALRI.LOCATION 
    and FALRI.COMPANY = gcc.segment1
    and FALRI.DEPRN_EXPENSE_ACCT = gcc.segment4
    and FALRI.COST_CENTER =  gcc.segment5
   order by FALRI.ASSET_NUMBER, FALRI.BOOK_TYPE_CODE