SELECT  
  'IMPLANTACÃO' MOVIMENTO, 
  AIA.INVOICE_TYPE_LOOKUP_CODE Tipo_de_Nota, 
  PV.VENDOR_NAME RAZAO_SOCIAL,  
  PV.SEGMENT1 COD_FORNEC, 
  AIA.INVOICE_NUM NR_NF ,
  AIA.CREATION_DATE ,
  cc.segment1 H1, 
  cc.segment2 H2, 
  cc.segment3 H3, 
  cc.segment4 H4, 
  cc.segment5 H5, 
  cc.segment6 H6, 
  cc.segment7 H7, 
  aia.invoice_amount, 
  AIA.EXCHANGE_RATE, 
  AIA.base_amount VALOR_CONTABIL_BRL, 
  XLL.currency_code, 
  nvl(XLL.ENTERED_DR, 0) DEBITO_ENTRADA, 
  nvl(XLL.ENTERED_CR,0) CREDITO_ENTRADA, 
  nvl(XLL.ACCOUNTED_DR, 0) DEBITO, 
  nvl(XLL.ACCOUNTED_CR,0) CREDITO, 
  XLL.DESCRIPTION DESCRICAO1,
  AID.DESCRIPTION DESCRICAO2,
  AIA.DESCRIPTION DESCRICAO3
FROM 
  APPS.AP_SUPPLIERS PV, 
  APPS.AP_INVOICES_ALL AIA, 
  APPS.AP_INVOICE_distributions_ALL AID, 
  APPS.GL_CODE_COMBINATIONS CC, 
  APPS.XLA_EVENTS XLE, 
  APPS.XLA_AE_HEADERS XLH, 
  APPS.XLA_AE_LINES XLL 
WHERE 
  AIA.VENDOR_ID = PV.VENDOR_ID 
  AND AIA.INVOICE_ID = AID.INVOICE_ID
  AND AID.INVOICE_LINE_NUMBER = 1
  AND AID.ACCOUNTING_EVENT_ID = XLE.EVENT_ID 
  AND XLH.EVENT_ID = XLE.EVENT_ID
  AND XLH.LEDGER_ID = 2021 
  AND XLL.AE_HEADER_ID = XLH.AE_HEADER_ID 
  AND XLL.CODE_COMBINATION_ID = CC.CODE_COMBINATION_ID
  order by AIA.INVOICE_NUM
  --AND AIA.INVOICE_NUM = '1515303094'