SELECT  DISTINCT
        FA.ASSET_ID "NUM ATIVO"
       ,SUBSTR(FA.DESCRIPTION,1,80) "DESC ATIVO"
       ,FCV.SEGMENT1 "CAT PRINCIPAL"
       ,FCV.SEGMENT1||' - '||FCV.SEGMENT2||' - '||FCV.SEGMENT3||' - '||FCV.SEGMENT4 "CAT ATIVO"
       ,FL.SEGMENT2||'-'||FL.SEGMENT3 "Local"
       ,FA.TAG_NUMBER "Etiqueta"
       ,SUBSTR(FB.BOOK_TYPE_CODE,1,15) LIVRO
       ,FAI.DATE_EFFECTIVE "DT AQUISICAO"
       ,FB.DATE_PLACED_IN_SERVICE "VALID ATIVO"
       ,FB.DEPRN_START_DATE "DT INI DEPR"
       ,FB.ORIGINAL_COST "VLR AQUIS"
       ,FBS.CALENDAR_PERIOD_OPEN_DATE "Periodo"
       --,FBS.PERIOD_NUM||'-'||FISCAL_YEAR "PERIODO"
       ,FBS.DEPRN_AMOUNT "DEPREC MES"
       ,FBS.YTD_DEPRN "DEPRE ANO"
       ,FBS.DEPRN_RESERVE "DEPR ACUMULADA"
       ,FBS.RECOVERABLE_COST-FBS.DEPRN_RESERVE "VLR LIQ"
       ,    Gcc.Segment1
         || '-'
         || Gcc.Segment2
         || '-'
         || Gcc.Segment3
         || '-'
         || Gcc.Segment4
         || '-'
         || Gcc.Segment5
         || '-'
         || Gcc.Segment6
         || '-'
         || Gcc.Segment7
            "CONTA CUSTO"
        ,   Gc1.Segment1
         || '-'
         || Gc1.Segment2
         || '-'
         || Gc1.Segment3
         || '-'
         || Gc1.Segment4
         || '-'
         || Gc1.Segment5
         || '-'
         || Gc1.Segment6
         || '-'
         || Gc1.Segment7
            "DEPREC ACUMULADA"
 FROM  apps.FA_CATEGORY_BOOKS FCB
      ,apps.FA_ADDITIONS FA
      ,apps.FA_BOOKS FB
      ,apps.FA_ASSET_INVOICES FAI
      ,apps.FA_BOOK_CONTROLS FBC
      ,apps.FA_ADDITIONS FA1
      ,apps.FA_DISTRIBUTION_HISTORY FDH
      ,APPS.FA_CATEGORIES_VL FCV
      ,APPS.FA_LOCATIONS FL
      ,APPS.FA_BOOKS_SUMMARY FBS
      ,APPS.GL_CODE_COMBINATIONS GCC
      ,APPS.GL_CODE_COMBINATIONS GC1
WHERE (1=1)
  AND FA.ASSET_CATEGORY_ID=FCB.CATEGORY_ID
  AND FA.ASSET_ID=FB.ASSET_ID
  AND FA1.ASSET_ID(+)=FA.PARENT_ASSET_ID
  AND FAI.ASSET_ID(+)=FA.ASSET_ID
  AND FCB.ASSET_COST_ACCOUNT_CCID = GCC.CODE_COMBINATION_ID
  AND FCB.RESERVE_ACCOUNT_CCID = GC1.CODE_COMBINATION_ID
  AND FB.BOOK_TYPE_CODE = FBC.BOOK_TYPE_CODE
  AND FB.TRANSACTION_HEADER_ID_OUT IS NULL
  AND FB.ORIGINAL_COST > 0
  --AND NVL (TRUNC (FAI.DATE_EFFECTIVE),TRUNC (FB.DATE_PLACED_IN_SERVICE)) BETWEEN TEMP.DATA_INI 
  AND FDH.ASSET_ID = FA.ASSET_ID
  AND FA.ASSET_CATEGORY_ID = FCV.CATEGORY_ID
  --AND SUBSTR(FBS.BOOK_TYPE_CODE,1,15) = SUBSTR(FB.BOOK_TYPE_CODE,1,15)
  AND FDH.LOCATION_ID = FL.LOCATION_ID
  AND FCV.CATEGORY_ID = FCB.CATEGORY_ID
  AND FCB.BOOK_TYPE_CODE = FBS.BOOK_TYPE_CODE
  AND FA.ASSET_ID = FBS.ASSET_ID
  AND FBC.BOOK_TYPE_CODE = FBS.BOOK_TYPE_CODE
  AND FBS.DEPRN_AMOUNT <> 0
  --AND FA.ASSET_ID = 128402
  ORDER BY FA.ASSET_ID, LIVRO