SELECT OOD.ORGANIZATION_NAME                  ORGANIZACAO
      --,FU.DESCRIPTION                         USUARUIO
      ,NVL(CFEO.SOURCE,'ENTRADA MANUAL')      TIPO_ENTRADA
      ,COUNT(*)
  FROM  APPS.CLL_F189_ENTRY_OPERATIONS        CFEO
      ,APPS.CLL_F189_INVOICES               CFI
      ,APPS.CLL_F189_INVOICE_LINES          CFIL
      ,APPS.CLL_F189_FISCAL_ENTITIES_ALL    CFFEA
      ,APPS.CLL_F189_INVOICE_TYPES          CFIT
      ,APPS.PO_VENDOR_SITES_ALL             PVSA
      ,APPS.PO_VENDORS                      PV
      ,APPS.ORG_ORGANIZATION_DEFINITIONS    OOD
      ,APPS.FND_USER                        FU
WHERE 1=1
 AND CFEO.OPERATION_ID       = CFI.OPERATION_ID
 AND CFEO.ORGANIZATION_ID    = CFI.ORGANIZATION_ID
 AND CFEO.LOCATION_ID        = CFI.LOCATION_ID
 AND CFI.INVOICE_ID          = CFIL.INVOICE_ID
 AND CFI.ORGANIZATION_ID     = CFIL.ORGANIZATION_ID
 AND CFI.ENTITY_ID           = CFFEA.ENTITY_ID
 AND CFI.INVOICE_TYPE_ID     = CFIT.INVOICE_TYPE_ID
 AND CFI.ORGANIZATION_ID     = CFIT.ORGANIZATION_ID
 AND CFFEA.VENDOR_SITE_ID    = PVSA.VENDOR_SITE_ID
 AND PVSA.VENDOR_ID          = PV.VENDOR_ID
 AND CFEO.ORGANIZATION_ID    = OOD.ORGANIZATION_ID
 AND CFI.ORGANIZATION_ID     = OOD.ORGANIZATION_ID
 AND CFIL.ORGANIZATION_ID    = OOD.ORGANIZATION_ID
 AND CFEO.CREATED_BY         = FU.USER_ID 
 AND NVL(CFEO.SOURCE,'ENTRADA MANUAL') IN ('ENTRADA MANUAL','NFEE','MANUAL','CTE')
 AND TRUNC(CFEO.RECEIVE_DATE) >= TO_DATE('01/01/2016','DD/MM/YYYY')
GROUP BY OOD.ORGANIZATION_NAME, CFEO.SOURCE --FU.DESCRIPTION
ORDER BY OOD.ORGANIZATION_NAME