SELECT FU.USER_NAME CRIADO_POR,
       FU.DESCRIPTION NOME,
       ood.organization_code,
       cfeo.operation_id,
       cfeo.receive_date,
       cfeo.GL_date,
       cfeo.status,
       cfeo.FREIGHT_FLAG Tipo_Frete,
       cfi.invoice_num,
       cfi.series,
       cfi.invoice_date,
       cfi.IMPORTATION_NUMBER DI_NUM,
       cfi.invoice_amount,
       cfi.icms_base,
       cfi.icms_tax,
       cfi.icms_amount,
       cfi.ipi_amount,
       cfi.subst_icms_base,
       cfi.subst_icms_amount,
       cfi.diff_icms_tax,
       cfi.diff_icms_amount,
       cfi.iss_Base,
       cfi.iss_amount,
       cfi.ir_base,
       cfi.ir_tax,
       cfi.ir_amount,
       cfi.irrf_base_date,
       cfi.inss_base,
       cfi.inss_amount,
       cfi.Ir_Vendor,
       cfi.ir_Categ,
       cfi.icms_St_base,
       cfi.icms_st_amount,
       cfi.icms_St_amount_recover,
       cfi.inss_autonomous_invoiced_total,
       cfi.inss_autonomous_amount,
       cfi.inss_autonomous_tax,            
       ap.vendor_name,
       assa.vendor_Site_Code,
       cffo.cfo_code,
       cffo.description,
       MSIB.SEGMENT1 CODIGO_ITEM,
       MSIB.DESCRIPTION DESCRICAO_ITEM,
        cfil.icms_base icms_base_linha,
        cfil.icms_tax icms_tax_linha,
        cfil.icms_amount icms_amount_linha,
        cfil.icms_amount_recover,
        cfil.icms_tax_code,
        cfil.diff_icms_tax diff_icms_tax_linha,
        cfil.diff_icms_amount diff_icms_amount_linha,
        cfil.ipi_base_amount,
        cfil.ipi_tax,
        cfil.ipi_amount ipi_amount_linha,
        cfil.ipi_amount_recover,
        cfil.ipi_tax_code,
        cfil.total_amount,
        cfil.icms_st_base icms_st_base_linha,
        cfil.icms_st_amount icms_st_amount_linha,
        cfil.icms_st_amount_recover icms_st_amount_recover_linha,
        cfil.pis_amount_recover,
        cfil.pis_cofins_st_base,
        cfil.pis_st_tax,
        cfil.pis_St_amount,
        cfil.cofins_St_tax,
        cfil.cofins_st_amount,
        cfil.cofins_amount_recover,
        cfil.importation_pis_cofins_base,
        cfil.importation_pis_amount,
        cfil.importation_cofins_amount,
        cfil.internal_icms_tax,
        cfil.Presumed_icms_tax_base,
        cfil.Presumed_icms_tax_perc,
        cfil.presumed_icms_tax_amount,
        cfil.iss_base_amount,
        cfil.iss_tax_rate,
        cfil.iss_tax_amount,
        cfil.ipi_tributary_code,
        cfil.ipi_tributary_type,
        cfil.pis_base_amount,
        cfil.pis_tax_rate,
        cfil.pis_amount,
        cfil.pis_tributary_code,
        cfil.cofins_base_amount,
        cfil.cofins_tax_rate,
        cfil.cofins_amount,
        cfil.cofins_tributary_code               
  FROM apps.cll_f189_invoices cfi,
       apps.cll_f189_entry_operations cfeo,
       apps.cll_f189_fiscal_entities_all cffea,
       apps.org_organization_definitions ood,
       apps.ap_suppliers ap,
       apps.MTL_SYSTEM_ITEMS_B MSIB,
       apps.ap_supplier_sites_all assa,
       apps.cll_f189_invoice_lines cfil,
       apps.FND_USER FU,
       apps.CLL_F189_FISCAL_OPERATIONS cffo
 WHERE     cfi.operation_id = cfeo.operation_id
       AND cfi.organization_id = cfeo.organization_id
       AND cfi.entity_id = cffea.entity_id
       AND cfi.organization_id = ood.organization_id
       AND CFIL.ITEM_ID = MSIB.INVENTORY_ITEM_ID(+)
       AND CFIL.ORGANIZATION_ID = MSIB.ORGANIZATION_ID(+)
       and ap.vendor_id = assa.vendor_id
       and assa.vendor_site_id = cffea.vendor_site_id  
       and cfi.invoice_id= cfil.invoice_id
       and cffo.cfo_id = cfil.cfo_id
       AND CFEO.CREATED_BY = FU.USER_ID
 order by receive_date