SELECT DISTINCT
        I.SOURCE ORIGEM,
        I.INTERFACE_OPERATION_ID OPERACAO_FISCAL,
        I.INTERFACE_INVOICE_ID DOCUMENTO_FISCAL,
        I.INVOICE_NUM NUM_DOC,
        I.INVOICE_AMOUNT VALOR_TOT,
        I.INVOICE_DATE DATA_DE_EMISSAO,
        I.GL_DATE DATA_GL,
        I.RECEIVE_DATE DATA_RECEBIMENTO,
        I.ORGANIZATION_CODE ORGANIZACAO,
        L.DESCRIPTION DESC_SERVICO,
        L.UNIT_PRICE VALOR_UNIT, 
        cc.segment1,
        cc.segment2,
        cc.segment3,
        cc.segment4,
        cc.segment5,
        cc.segment6,
        cc.segment7,
        I.PROCESS_FLAG CODIGO_STATUS,
        I.DOCUMENT_NUMBER CNPJ_FORNECEDOR,
        E.ERROR_CODE,
        E.ERROR_MESSAGE,
        E.INVALID_VALUE DESCRICAO_ERRO
FROM    APPS.CLL_F189_INVOICES_INTERFACE I, 
        APPS.CLL_F189_INVOICE_LINES_IFACE L,
        APPS.CLL_F189_INTERFACE_ERRORS E, 
        APPS.GL_CODE_COMBINATIONS CC
WHERE   I.SOURCE = 'PSFRETE' 
  AND (I.PROCESS_FLAG <> '6' OR I.PROCESS_FLAG IS NULL)
  AND I.INTERFACE_INVOICE_ID =  E.INTERFACE_INVOICE_ID
  AND I.INTERFACE_INVOICE_ID =  L.INTERFACE_INVOICE_ID
  AND L.db_code_combination_id = CC.CODE_COMBINATION_ID
  ORDER BY INVOICE_NUM;
