SELECT DISTINCT RCT.CUSTOMER_TRX_ID"ID NF",
       RCT.TRX_NUMBER"NRO NF",
       RTT.NAME"NOME TIPO TRANSACAO",
       DECODE(RTT.TYPE, 'INV', 'NFF', 'CM','AV CREDITO', 'DM','AV DEBITO')"TIPO TRANSACAO",
       RBS.NAME "Origem",
       RCT.TRX_DATE"DATA NFF",
       RCT.CREATION_DATE"DATA CRIACAO NF",
       DECODE(RCT.STATUS_TRX,'VD','CANCELADA','EMITIDA') "Status",
       JCT.ELECTRONIC_INV_ACCESS_KEY"CHAVE ELETRONICA",
       DECODE(JCT.ELECTRONIC_INV_STATUS, 1, 'Enviado', 2, 'Finalizado', 3, 'Erro', 4, 'Cancelado', 5, 'Rejeitado pela SEFAZ', 6, 'Obsoleto') "STATUS NFE",
       JBE.MESSAGE_TXT"Mensagem"
  FROM APPS.RA_CUSTOMER_TRX_ALL   RCT,
       APPS.RA_BATCH_SOURCES_ALL  RBS,
       APPS.JL_BR_CUSTOMER_TRX_EXTS JCT,
       APPS.RA_CUST_TRX_TYPES_ALL RTT,
       APPS.JL_BR_EILOG JBE
 WHERE RCT.BATCH_SOURCE_ID = RBS.BATCH_SOURCE_ID
   AND RCT.CUST_TRX_TYPE_ID = RTT.CUST_TRX_TYPE_ID
   AND RCT.CUSTOMER_TRX_ID = JCT.CUSTOMER_TRX_ID 
   and RCT.CUSTOMER_TRX_ID = JBE.CUSTOMER_TRX_ID 
   AND JCT.ELECTRONIC_INV_STATUS NOT IN (2, 4, 6)
   AND NVL(RBS.ORG_ID, -1) > 0
   AND RTT.TYPE <> 'CM'
   AND RCT.COMPLETE_FLAG = 'Y'
ORDER BY RCT.TRX_NUMBER ASC