SELECT OOD.ORGANIZATION_CODE                  ORG_CODE
      ,OOD.ORGANIZATION_NAME                  ORGANIZACAO
      ,FU.USER_NAME || ' - ' || FU.DESCRIPTION USUARUIO
      ,CFEO.OPERATION_ID                      NUM_REC
      ,CFEO.RECEIVE_DATE                      DT_REC
      ,CFEO.GL_DATE                           DT_GL
      ,CFEO.STATUS
      ,NVL(CFEO.SOURCE,'ENTRADA MANUAL')      TIPO_ENTRADA
      ,CFI.INVOICE_NUM                        NUM_NF
      ,CFI.GROSS_TOTAL_AMOUNT                 VLR_TOTAL_NF
      ,CFI.ELETRONIC_INVOICE_KEY              CHAVE_ACESSO
      ,PV.VENDOR_NAME                         NOME_FORNEC
      ,PVSA.VENDOR_SITE_CODE                  LOCAL_FORNECEOR
      ,CFI.FISCAL_DOCUMENT_MODEL              ESPECIE
      ,CFIT.INVOICE_TYPE_CODE                 TP_NF
      ,CFI.INVOICE_DATE                       DT_EMISSAO
FROM  APPS.CLL_F189_ENTRY_OPERATIONS        CFEO
      ,APPS.CLL_F189_INVOICES               CFI
      ,APPS.CLL_F189_INVOICE_LINES          CFIL
      ,APPS.CLL_F189_FISCAL_ENTITIES_ALL    CFFEA
      ,APPS.CLL_F189_INVOICE_TYPES          CFIT
      ,APPS.PO_VENDOR_SITES_ALL             PVSA
      ,APPS.PO_VENDORS                      PV
      ,APPS.ORG_ORGANIZATION_DEFINITIONS    OOD
      ,APPS.FND_USER                        FU
WHERE 1=1
 AND CFEO.OPERATION_ID       = CFI.OPERATION_ID
 AND CFEO.ORGANIZATION_ID    = CFI.ORGANIZATION_ID
 AND CFEO.LOCATION_ID        = CFI.LOCATION_ID
 AND CFI.INVOICE_ID          = CFIL.INVOICE_ID
 AND CFI.ORGANIZATION_ID     = CFIL.ORGANIZATION_ID
 AND CFI.ENTITY_ID           = CFFEA.ENTITY_ID
 AND CFI.INVOICE_TYPE_ID     = CFIT.INVOICE_TYPE_ID
 AND CFI.ORGANIZATION_ID     = CFIT.ORGANIZATION_ID
 AND CFFEA.VENDOR_SITE_ID    = PVSA.VENDOR_SITE_ID
 AND PVSA.VENDOR_ID          = PV.VENDOR_ID
 AND CFEO.ORGANIZATION_ID    = OOD.ORGANIZATION_ID
 AND CFI.ORGANIZATION_ID     = OOD.ORGANIZATION_ID
 AND CFIL.ORGANIZATION_ID    = OOD.ORGANIZATION_ID
 AND CFEO.CREATED_BY         = FU.USER_ID 
 AND NVL(CFEO.SOURCE,'ENTRADA MANUAL') IN ('ENTRADA MANUAL','NFEE','MANUAL','CTE')
 AND TRUNC(CFEO.RECEIVE_DATE) >= TO_DATE('01/01/2016','DD/MM/YYYY')
 ORDER BY CFEO.RECEIVE_DATE DESC