SELECT N.ORGANIZATION_ID,N.NNF,N.STATUS,N.SERIE,N.CNPJ_EMIT,N.CNPJ_DEST,N.CHAVE,N.DEMI,N.NOME_ARQ,N.NOME_DEST,N.XLGR_DEST,N.XMUN_DEST,N.NOME_EMIT,N.XLGR_EMIT
,N.XMUN_EMIT,N.SOURCE,N.CREATION_DATE,N.TIPO_NF,N.NATOP,N.STATUS_SEFAZ,N.FILE_TYPE
  FROM XXSN.NFEE_HEADER_XML N
WHERE 1=1
AND   N.CHAVE IS NULL
AND   N.FILE_TYPE NOT IN ('Xml_Abrasf', 'Serv_txt', 'Xml_Serv')
AND   N.STATUS = 'PENDENTE'