SELECT DISTINCT
         OEH.ORDER_NUMBER "NUMERO RMA",
         TRUNC(OEH.ORDERED_DATE) "DATA RMA",
         USERS.USER_NAME || ' - ' || USERS.DESCRIPTION "CRIADO POR",
         PARTY.PARTY_NAME CLIENTE,
         SUBSTR(HCSUA.LOCATION,1,INSTR(HCSUA.LOCATION,'_',1)-1) CNPJ,         
         TT.NAME "TIPO TRANSACAO OM",
         OEH.SALES_CHANNEL_CODE "CANAL VENDA",
          (select sum ((OL.ORDERED_QUANTITY * OL.UNIT_SELLING_PRICE) + OL.TAX_VALUE)from APPS.OE_ORDER_LINES_ALL OL where OEL.HEADER_ID = OL.HEADER_ID) "VALOR TOTAL RMA",
         MP.ORGANIZATION_CODE ORGANIZACAO,
         OEL.FLOW_STATUS_CODE "SITUACAO LINHA RMA",
         WFD.DISPLAY_NAME "DETALHE WORKFLOW",
         (SELECT H.TRX_NUMBER || ' - ' || SOURCE.NAME
            FROM APPS.RA_CUSTOMER_TRX_ALL H,
                 APPS.RA_CUSTOMER_TRX_LINES_ALL L,
                 APPS.RA_BATCH_SOURCES_ALL SOURCE
           WHERE     H.CUSTOMER_TRX_ID = L.CUSTOMER_TRX_ID
                 AND L.CUSTOMER_TRX_LINE_ID =
                        OEL.REFERENCE_CUSTOMER_TRX_LINE_ID
                 AND H.BATCH_SOURCE_ID = SOURCE.BATCH_SOURCE_ID
                 AND H.ORG_ID          = SOURCE.ORG_ID)
            "NF VENDA",
              (SELECT L.EXTENDED_AMOUNT
            FROM APPS.RA_CUSTOMER_TRX_ALL H,
                 APPS.RA_CUSTOMER_TRX_LINES_ALL L,
                 APPS.RA_BATCH_SOURCES_ALL SOURCE
           WHERE     H.CUSTOMER_TRX_ID = L.CUSTOMER_TRX_ID
                 AND L.CUSTOMER_TRX_LINE_ID =
                        OEL.REFERENCE_CUSTOMER_TRX_LINE_ID
                 AND H.BATCH_SOURCE_ID = SOURCE.BATCH_SOURCE_ID
                 AND H.ORG_ID          = SOURCE.ORG_ID)
            "VALOR NF VENDA",
         (SELECT H.TRX_NUMBER || ' - ' || SOURCE.NAME
            FROM APPS.RA_CUSTOMER_TRX_ALL H,
                 APPS.RA_CUSTOMER_TRX_LINES_ALL L,
                 APPS.RA_BATCH_SOURCES_ALL SOURCE
           WHERE     H.CUSTOMER_TRX_ID = L.CUSTOMER_TRX_ID
                 AND to_number (L.INTERFACE_LINE_ATTRIBUTE6)= OEL.LINE_ID
                 AND L.LINE_TYPE = 'LINE'
                 AND TO_CHAR (OEH.ORDER_NUMBER) = H.INTERFACE_HEADER_ATTRIBUTE1
                 AND H.INTERFACE_HEADER_CONTEXT = 'NF ENTRADA AR'
                 AND H.BATCH_SOURCE_ID = SOURCE.BATCH_SOURCE_ID
                 AND H.ORG_ID          = SOURCE.ORG_ID)
            "NF RECUSA",
         (SELECT    'NUM RECEBIMENTO: '
                 || SHIPM.RECEIPT_NUM
                 || ' - NUM NF ENT: '
                 || INV.INVOICE_NUM
            FROM APPS.RCV_TRANSACTIONS RT,
                 APPS.RCV_SHIPMENT_HEADERS SHIPM,
                 APPS.CLL_F189_INVOICES INV
           WHERE     OE_ORDER_LINE_ID = OEL.LINE_ID
                 AND RT.SOURCE_DOCUMENT_CODE = 'RMA'
                 AND RT.TRANSACTION_TYPE = 'RECEIVE'
                 AND SHIPM.SHIPMENT_HEADER_ID = RT.SHIPMENT_HEADER_ID
                 AND SHIPM.RECEIPT_NUM = INV.OPERATION_ID
                 AND SHIPM.ORGANIZATION_ID = INV.ORGANIZATION_ID
                 AND ROWNUM = 1)
            "DETALHE REC FISCAL",
             (SELECT  INV.INVOICE_AMOUNT
            FROM APPS.RCV_TRANSACTIONS RT,
                 APPS.RCV_SHIPMENT_HEADERS SHIPM,
                 APPS.CLL_F189_INVOICES INV
           WHERE     OE_ORDER_LINE_ID = OEL.LINE_ID
                 AND RT.SOURCE_DOCUMENT_CODE = 'RMA'
                 AND RT.TRANSACTION_TYPE = 'RECEIVE'
                 AND SHIPM.SHIPMENT_HEADER_ID = RT.SHIPMENT_HEADER_ID
                 AND SHIPM.RECEIPT_NUM = INV.OPERATION_ID
                 AND SHIPM.ORGANIZATION_ID = INV.ORGANIZATION_ID
                 AND ROWNUM = 1)
            "VALOR NF ENTRADA",
        (SELECT cfi.INVOICE_NUM ||' - '|| cfit.invoice_type_code from APPS.CLL_F189_INVOICES cfi,CLL_F189_INVOICE_TYPES cfit WHERE cfi.ATTRIBUTE6 
           in (SELECT SHIPM.RECEIPT_NUM           
            FROM APPS.RCV_TRANSACTIONS RT,
                 APPS.RCV_SHIPMENT_HEADERS SHIPM,
                 APPS.CLL_F189_INVOICES INV
           WHERE     RT.OE_ORDER_LINE_ID = OEL.LINE_ID
                 AND RT.SOURCE_DOCUMENT_CODE = 'RMA'
                 AND RT.TRANSACTION_TYPE = 'RECEIVE'
                 AND SHIPM.SHIPMENT_HEADER_ID = RT.SHIPMENT_HEADER_ID
                 AND SHIPM.RECEIPT_NUM = INV.OPERATION_ID
                 AND SHIPM.ORGANIZATION_ID = INV.ORGANIZATION_ID
                 AND ROWNUM = 1) AND cfi.ORGANIZATION_ID = MP.ORGANIZATION_ID 
                 and cfit.INVOICE_TYPE_ID = cfi.INVOICE_TYPE_ID) "NF COMPLEM-TIPO NF",  
    (SELECT INVOICE_AMOUNT from APPS.CLL_F189_INVOICES WHERE ATTRIBUTE6 in (SELECT SHIPM.RECEIPT_NUM           
            FROM APPS.RCV_TRANSACTIONS RT,
                 APPS.RCV_SHIPMENT_HEADERS SHIPM,
                 APPS.CLL_F189_INVOICES INV
           WHERE     RT.OE_ORDER_LINE_ID = OEL.LINE_ID
                 AND RT.SOURCE_DOCUMENT_CODE = 'RMA'
                 AND RT.TRANSACTION_TYPE = 'RECEIVE'
                 AND SHIPM.SHIPMENT_HEADER_ID = RT.SHIPMENT_HEADER_ID
                 AND SHIPM.RECEIPT_NUM = INV.OPERATION_ID
                 AND SHIPM.ORGANIZATION_ID = INV.ORGANIZATION_ID
                 AND ROWNUM = 1) AND ORGANIZATION_ID = MP.ORGANIZATION_ID) "VALOR NF COMPLEM",    
         (SELECT 'SIM'
            FROM APPS.RCV_TRANSACTIONS
           WHERE     OE_ORDER_LINE_ID = OEL.LINE_ID
                 AND SOURCE_DOCUMENT_CODE = 'RMA'
                 AND TRANSACTION_TYPE = 'DELIVER') "REC FISICO CONCLUIDO ?",
         (SELECT 'SIM'
            FROM APPS.RA_INTERFACE_LINES_ALL
           WHERE     INTERFACE_LINE_CONTEXT = 'ORDER ENTRY'
                 AND INTERFACE_LINE_ATTRIBUTE1 = TO_CHAR (OEH.ORDER_NUMBER)
                 AND INTERFACE_LINE_ATTRIBUTE2 = TT.NAME
                 AND to_number (INTERFACE_LINE_ATTRIBUTE6)= OEL.LINE_ID
                 AND SALES_ORDER = OEH.ORDER_NUMBER
                 AND LINE_TYPE = 'LINE') "RMA INSERIDO INT NF ?",
         (SELECT H.TRX_NUMBER
            FROM APPS.RA_CUSTOMER_TRX_ALL H, APPS.RA_CUSTOMER_TRX_LINES_ALL L
           WHERE     H.CUSTOMER_TRX_ID = L.CUSTOMER_TRX_ID
                 AND to_number (L.INTERFACE_LINE_ATTRIBUTE6) = OEL.LINE_ID
                 AND L.LINE_TYPE = 'LINE'
                 AND TO_CHAR (OEH.ORDER_NUMBER) = H.INTERFACE_HEADER_ATTRIBUTE1
                 AND H.INTERFACE_HEADER_CONTEXT = 'ORDER ENTRY'
                 AND ROWNUM = 1) "NUM AVISO CREDITO",
           (SELECT SUM (L.EXTENDED_AMOUNT)
            FROM APPS.RA_CUSTOMER_TRX_ALL H, APPS.RA_CUSTOMER_TRX_LINES_ALL L
           WHERE     H.CUSTOMER_TRX_ID = L.CUSTOMER_TRX_ID
                 AND to_number (L.INTERFACE_LINE_ATTRIBUTE6) = OEL.LINE_ID
                 AND L.LINE_TYPE = 'LINE'
                 AND TO_CHAR (OEH.ORDER_NUMBER) = H.INTERFACE_HEADER_ATTRIBUTE1
                 AND H.INTERFACE_HEADER_CONTEXT = 'ORDER ENTRY'
                 ) "VALOR AVISO CREDITO"                                             
    FROM APPS.OE_ORDER_HEADERS_ALL OEH,
         APPS.OE_ORDER_LINES_ALL OEL,
         APPS.MTL_PARAMETERS MP,
         APPS.OE_TRANSACTION_TYPES_TL TT,
         APPS.OE_WORKFLOW_ASSIGNMENTS WF,
         APPS.WF_RUNNABLE_PROCESSES_V WFD,
         APPS.HZ_LOCATIONS HL,         
         APPS.HZ_CUST_SITE_USES_ALL HCSUA,
         APPS.HZ_CUST_ACCT_SITES_ALL HCASA,
         APPS.HZ_PARTY_SITES HPS,
         APPS.HZ_CUST_ACCOUNTS CUST_ACCT,
         APPS.HZ_PARTIES PARTY,
         APPS.FND_USER USERS
   WHERE     OEH.CREATED_BY = USERS.USER_ID
         AND OEL.SHIP_FROM_ORG_ID = MP.ORGANIZATION_ID
         AND WFD.ITEM_TYPE = 'OEOL'
         AND  TRUNC(OEH.ORDERED_DATE) BETWEEN TRUNC(NVL(WF.START_DATE_ACTIVE,SYSDATE)) AND TRUNC(NVL(WF.END_DATE_ACTIVE,SYSDATE))
         AND WF.PROCESS_NAME = WFD.PROCESS_NAME
         AND OEL.LINE_TYPE_ID = WF.LINE_TYPE_ID
         AND HPS.LOCATION_ID = HL.LOCATION_ID
         AND HCSUA.SITE_USE_CODE = 'SHIP_TO'         
         AND HCSUA.CUST_ACCT_SITE_ID = HCASA.CUST_ACCT_SITE_ID
         AND HCASA.PARTY_SITE_ID = HPS.PARTY_SITE_ID
         AND HPS.PARTY_ID = PARTY.PARTY_ID         
         AND OEH.SHIP_TO_ORG_ID = HCSUA.SITE_USE_ID
         AND CUST_ACCT.PARTY_ID = PARTY.PARTY_ID
         AND OEH.SOLD_TO_ORG_ID = CUST_ACCT.CUST_ACCOUNT_ID
         AND OEH.HEADER_ID = OEL.HEADER_ID
         AND OEH.ORDER_TYPE_ID = TT.TRANSACTION_TYPE_ID
         AND TT.NAME LIKE '%RMA%';