SELECT NHX.NNF NR_CTE
      ,NHX.CHAVE CHAVE_ACESSO
      ,NHX.STATUS || ' - ' || STATUS_SEFAZ STATUS_CTE
      ,NHX.DEMI DT_EMISSAO
      ,DECODE(NHX.TIPO_OP, 'S','SAIDA','E','ENTRADA') TIPO_CTE
      ,NHX.TIPO_TOMA_SERV TAG_TOMA
      ,NHX.CNPJ_EMIT
      ,NHX.NOME_EMIT NOME_FORNECEDOR
      ,NHX.CNPJ_DEST
      ,HL.DESCRIPTION LOCAL_RECEBIMENTO
  FROM APPS.NFEE_HEADER_XML NHX
      ,APPS.HR_LOCATIONS HL
 WHERE 1=1
 AND   NHX.LOCATION_ID =  HL.LOCATION_ID
 AND   NHX.SOURCE      =  'CTE'
 AND   NHX.STATUS      <> 'PROCESSADO'
 ORDER BY NHX.DEMI DESC