SELECT APSA.INVOICE_ID
,APSA.LAST_UPDATED_BY                             
,APSA.LAST_UPDATE_DATE           
,APSA.PAYMENT_CROSS_RATE         
,APSA.PAYMENT_NUM                
,APSA.AMOUNT_REMAINING           
,APSA.CREATED_BY                 
,APSA.CREATION_DATE              
,APSA.DISCOUNT_DATE              
,APSA.DUE_DATE                   
,APSA.FUTURE_PAY_DUE_DATE        
,APSA.GROSS_AMOUNT               
,APSA.HOLD_FLAG                  
,APSA.LAST_UPDATE_LOGIN          
,APSA.PAYMENT_METHOD_LOOKUP_CODE 
,APSA.PAYMENT_PRIORITY           
,APSA.PAYMENT_STATUS_FLAG        
,APSA.SECOND_DISCOUNT_DATE       
,APSA.THIRD_DISCOUNT_DATE        
,APSA.BATCH_ID                   
,APSA.DISCOUNT_AMOUNT_AVAILABLE  
,APSA.SECOND_DISC_AMT_AVAILABLE  
,APSA.THIRD_DISC_AMT_AVAILABLE   
,APSA.ATTRIBUTE1                 
,APSA.ATTRIBUTE10                
,APSA.ATTRIBUTE11                
,APSA.ATTRIBUTE12                
,APSA.ATTRIBUTE13                
,APSA.ATTRIBUTE14                
,APSA.ATTRIBUTE15                
,APSA.ATTRIBUTE2                 
,APSA.ATTRIBUTE3                 
,APSA.ATTRIBUTE4                 
,APSA.ATTRIBUTE5                 
,APSA.ATTRIBUTE6                 
,APSA.ATTRIBUTE7                 
,APSA.ATTRIBUTE8                 
,APSA.ATTRIBUTE9                 
,APSA.ATTRIBUTE_CATEGORY         
,APSA.DISCOUNT_AMOUNT_REMAINING  
,APSA.ORG_ID                     
,APSA.GLOBAL_ATTRIBUTE_CATEGORY  
,APSA.GLOBAL_ATTRIBUTE1          
,APSA.GLOBAL_ATTRIBUTE2          
,APSA.GLOBAL_ATTRIBUTE3          
,APSA.GLOBAL_ATTRIBUTE4          
,APSA.GLOBAL_ATTRIBUTE5          
,APSA.GLOBAL_ATTRIBUTE6          
,APSA.GLOBAL_ATTRIBUTE7          
,APSA.GLOBAL_ATTRIBUTE8          
,APSA.GLOBAL_ATTRIBUTE9          
,APSA.GLOBAL_ATTRIBUTE10         
,APSA.GLOBAL_ATTRIBUTE11         
,APSA.GLOBAL_ATTRIBUTE12         
,APSA.GLOBAL_ATTRIBUTE13         
,APSA.GLOBAL_ATTRIBUTE14         
,APSA.GLOBAL_ATTRIBUTE15         
,APSA.GLOBAL_ATTRIBUTE16         
,APSA.GLOBAL_ATTRIBUTE17         
,APSA.GLOBAL_ATTRIBUTE18         
,APSA.GLOBAL_ATTRIBUTE19         
,APSA.GLOBAL_ATTRIBUTE20         
,APSA.EXTERNAL_BANK_ACCOUNT_ID   
,APSA.INV_CURR_GROSS_AMOUNT      
,APSA.CHECKRUN_ID                
,APSA.DBI_EVENTS_COMPLETE_FLAG   
,APSA.IBY_HOLD_REASON            
,APSA.PAYMENT_METHOD_CODE        
,APSA.REMITTANCE_MESSAGE1        
,APSA.REMITTANCE_MESSAGE2        
,APSA.REMITTANCE_MESSAGE3        
,APSA.REMIT_TO_SUPPLIER_NAME     
,APSA.REMIT_TO_SUPPLIER_ID       
,APSA.REMIT_TO_SUPPLIER_SITE     
,APSA.REMIT_TO_SUPPLIER_SITE_ID  
,APSA.RELATIONSHIP_ID    
,AIA.INVOICE_NUM        
,AIA.INVOICE_CURRENCY_CODE
,AIA.PAYMENT_CURRENCY_CODE
,AIA.INVOICE_AMOUNT
,AIA.AMOUNT_PAID
,AIA.INVOICE_DATE
,AIA.SOURCE
,AIA.INVOICE_TYPE_LOOKUP_CODE
,AIA.AMOUNT_APPLICABLE_TO_DISCOUNT
,AIA.TERMS_ID
,AIA.TERMS_DATE
,AIA.PAY_GROUP_LOOKUP_CODE
,AIA.INVOICE_RECEIVED_DATE
,AIA.APPROVED_AMOUNT
,PV.VENDOR_NAME
,PV.SEGMENT1 "NUMERO FORNECEDOR"

,SLA_CONTA.ACCOUNTING_COMBINATION
,SLA_CONTA.CONTA
,SLA_CONTA.ACCOUNTING_DATE
,SLA_CONTA.STATUS_POSTED
,SLA_CONTA.CREDIT_AMOUNT
,SLA_CONTA.DEBIT_AMOUNT

FROM AP_PAYMENT_SCHEDULES_ALL APSA
  ,AP_INVOICES_ALL AIA
  ,PO_VENDORS PV
  ,PO_VENDOR_SITES_ALL PVSA   
  
  ,(SELECT  DISTINCT GCC.SEGMENT1||'.'||GCC.SEGMENT2||'.'||GCC.SEGMENT3||'.'||GCC.SEGMENT4||'.'||GCC.SEGMENT5||'.'||GCC.SEGMENT6||'.'||GCC.SEGMENT7
||'.'||GCC.SEGMENT8||'.'||GCC.SEGMENT9 ACCOUNTING_COMBINATION
,( SELECT FFV.FLEX_VALUE||' - '||FFVT.DESCRIPTION  CONTA   
         FROM FND_FLEX_VALUES FFV ,FND_FLEX_VALUES_TL FFVT
        WHERE FFV.FLEX_VALUE_ID = FFVT.FLEX_VALUE_ID          
          AND FFVT.LANGUAGE = 'PTB'
          AND FFV.FLEX_VALUE = GCC.SEGMENT4
          AND ROWNUM = 1) CONTA 
,AIDA.ACCOUNTING_DATE  ACCOUNTING_DATE
,DECODE(AIDA.POSTED_FLAG,'P','Posted','Unposted') STATUS_POSTED
,AALA.ACCOUNTED_CR CREDIT_AMOUNT
,AALA.ACCOUNTED_DR DEBIT_AMOUNT
,AIAA.INVOICE_ID
FROM 
AP_INVOICE_DISTRIBUTIONS_ALL  AIDA
,XLA_AE_HEADERS             AAHA
,XLA_AE_LINES               AALA
,GL_CODE_COMBINATIONS          GCC
,AP_INVOICES_ALL               AIAA
WHERE 1 = 1
AND AAHA.AE_HEADER_ID               = AALA.AE_HEADER_ID
AND AAHA.EVENT_ID = AIDA.ACCOUNTING_EVENT_ID(+)
AND AIDA.LINE_TYPE_LOOKUP_CODE      = 'ITEM'
AND AIDA.DIST_CODE_COMBINATION_ID   = GCC.CODE_COMBINATION_ID
AND AIAA.INVOICE_ID                  = AIDA.INVOICE_ID) SLA_CONTA
     
WHERE AIA.INVOICE_ID = APSA.INVOICE_ID
AND PV.VENDOR_ID = AIA.VENDOR_ID   
AND PVSA.VENDOR_ID = PV.VENDOR_ID 
AND AIA.VENDOR_SITE_ID = PVSA.VENDOR_SITE_ID      

AND SLA_CONTA.INVOICE_ID (+) = AIA.INVOICE_ID