SELECT DISTINCT RL.INTERFACE_LINE_ID
      , RL.BATCH_SOURCE_NAME ORIGEM
      , RL.INTERFACE_LINE_ATTRIBUTE1 ORDEM_VENDA
      , RL.INTERFACE_LINE_ATTRIBUTE2 TIPO_ORDEM_VENDA
      , RL.CREATION_DATE DATA_CRIACAO
      , RE.MESSAGE_TEXT MSG_TEXTO_ERRO
      , RE.INVALID_VALUE VALOR_INVALIDO
   FROM APPS.RA_INTERFACE_LINES_ALL RL
      , APPS.RA_INTERFACE_ERRORS_ALL RE
  WHERE RL.INTERFACE_LINE_ID = RE.INTERFACE_LINE_ID (+)
    AND REQUEST_ID IS NULL
    AND INTERFACE_STATUS IS NULL
ORDER BY RL.INTERFACE_LINE_ATTRIBUTE1