SELECT DISTINCT (SELECT SEGMENT6 FROM GL_CODE_COMBINATIONS
         WHERE CODE_COMBINATION_ID = JRS.GL_ID_REV) "UNIDADE DE NEGOCIO"
      ,(SELECT NAME FROM HR_ALL_ORGANIZATION_UNITS
        WHERE ORGANIZATION_ID = RCTLA.WAREHOUSE_ID) ESTABELECIMENTO     
      ,HCA.ACCOUNT_NUMBER "COD CLIENTE"
      ,HP.PARTY_NAME "NOME DO CLIENTE"
      ,(SELECT decode(substr(ARM.NAME ,-4,4),'CART','CARTEIRA','ESCR','ESCRITURAL','VEND','VENDOR')
          FROM JL_BR_AR_COLLECTION_DOCS_ALL JBACDA  
              ,AR_RECEIPT_METHODS ARM
         WHERE JBACDA.PAYMENT_SCHEDULE_ID = APSA.PAYMENT_SCHEDULE_ID     
           AND JBACDA.CUSTOMER_TRX_ID =  RCTA.CUSTOMER_TRX_ID  
           AND ARM.RECEIPT_METHOD_ID = JBACDA.RECEIPT_METHOD_ID   
           AND ROWNUM = 1) CARTEIRA
           
      --LIQUIDACAO PARCIAL
 
      ,(SELECT DOCUMENT_ID 
         FROM JL_BR_AR_COLLECTION_DOCS_ALL
        WHERE PAYMENT_SCHEDULE_ID = APSA.PAYMENT_SCHEDULE_ID
          AND CUSTOMER_TRX_ID =  RCTA.CUSTOMER_TRX_ID
          AND ROWNUM = 1) "TITULO BANCO"
      ,APSA.INVOICE_CURRENCY_CODE MOEDA    
      ,TRUNC(APSA.CREATION_DATE) "DATA EMISSAO DO TITULO"
      ,RCTTA.NAME "TIPO DE NOTA"
      ,RBSA.GLOBAL_ATTRIBUTE3 "SERIE DO DOCUMENTO"
      ,RCTTA.DESCRIPTION "DESCRICAO DO DOCUMENTO"
      ,RCTA.TRX_NUMBER "TITULO - NUMERO DA NF"      
      ,APSA.TERMS_SEQUENCE_NUMBER PARCELA
      ,APSA.AMOUNT_DUE_ORIGINAL "VALOR ORIGINAL DO TITULO"
      ,APSA.AMOUNT_DUE_REMAINING "VALOR SALDO"
      --,APSA.AMOUNT_DUE_REMAINING "VALOR PENDENTE"
      ,APSA.AMOUNT_DUE_ORIGINAL "VALOR LIQUIDACAO"
      ,APSA.DISCOUNT_ORIGINAL "VALOR DO DESCONTO"
      ,(100*NVL(APSA.DISCOUNT_ORIGINAL,0)) / APSA.AMOUNT_DUE_ORIGINAL "% DESCONTO"
      ,TRUNC(APSA.DUE_DATE) "DATA DO VENCIMENTO"
      --DATA DO CREDITO DO PAGAMENTO    DATA DA LIQUIDACAO
      --,RCTTA.NAME "TIPO LIQUIDACAO"
      --REFERENCIA DA LIQUIDACAO    REFERENCIA DA LIQUIDACAO
      ,APSA.DUE_DATE - SYSDATE "DIAS ATE VENCER"
      --,"DATA DO PAGAMENTO/LIQUIDACAO" VERIRICAR
      --,USUARIO QUE LIQUIDOU
      
      ,HP.ATTRIBUTE2 "GRUPO DO CLIENTE"
            
       ,(SELECT ARM.NAME 
          FROM JL_BR_AR_COLLECTION_DOCS_ALL JBACDA  
              ,AR_RECEIPT_METHODS ARM
         WHERE JBACDA.PAYMENT_SCHEDULE_ID = APSA.PAYMENT_SCHEDULE_ID     
           AND JBACDA.CUSTOMER_TRX_ID =  RCTA.CUSTOMER_TRX_ID  
           AND ARM.RECEIPT_METHOD_ID = JBACDA.RECEIPT_METHOD_ID   
           AND ROWNUM = 1) PORTADOR    

      ,HCP.PHONE_AREA_CODE||' - '||HCP.PHONE_NUMBER FONE
      ,HL.CITY "CIDADE DE COBRANCA"      
      ,HL.ADDRESS1 ENDERECO1
      ,HL.ADDRESS2 ENDERECO2
      ,HL.ADDRESS3 ENDERECO3
      ,HL.ADDRESS4 ENDERECO4
      ,HL.CITY     CIDADE
      --,HL.STATE    ESTADO
      ,HL.POSTAL_CODE CEP
      
      ,HCASA.GLOBAL_ATTRIBUTE3||HCASA.GLOBAL_ATTRIBUTE4||HCASA.GLOBAL_ATTRIBUTE5 CNPJ
      ,HL.STATE UF
      ,TO_CHAR(HCA.CREATION_DATE,'DD/MM/RRRR') "DATA IMPLANTACAO CLIENTE"
      
      ,HCPROF.NEXT_CREDIT_REVIEW_DATE "DATA DO LIMITE DE CREDITO"
      ,HCPA.OVERALL_CREDIT_LIMIT "VALOR LIMITE CREDITO ATUAL"
      --DATA DA ULTIMA ALTERACAO(REVISAO) DO LIMITE
      --LIMITE ANTERIOR(QUERY ENVIADA)
      --USUARIO QUE ALTEROU(NA TABELA DE RECOMENDACAO TB)
      ,NVL(NVL((SELECT TRUNC(MIN(CREATION_DATE))
                     FROM  OE_ORDER_HEADERS_ALL
                   WHERE SALESREP_ID = RCTA.PRIMARY_SALESREP_ID),
                  (SELECT MIN(CREATION_DATE) 
                                  FROM  OE_ORDER_HEADERS_ALL
                                  WHERE SOLD_TO_ORG_ID = HCA.CUST_ACCOUNT_ID)),
                                  (SELECT MIN(CREATION_DATE)
                                    FROM RA_CUSTOMER_TRX_ALL
                                    WHERE BILL_TO_CUSTOMER_ID = RCTA.BILL_TO_CUSTOMER_ID)                                  
                                  ) "DATA PRIMEIRA COMPRA"
      ,NVL(NVL((SELECT TRUNC(MAX(CREATION_DATE))
                     FROM  OE_ORDER_HEADERS_ALL
   WHERE SALESREP_ID = RCTA.PRIMARY_SALESREP_ID),
                  (SELECT MAX(CREATION_DATE) 
                                  FROM  OE_ORDER_HEADERS_ALL
                                  WHERE SOLD_TO_ORG_ID = HCA.CUST_ACCOUNT_ID)),
                                  (SELECT MAX(CREATION_DATE)
                                    FROM RA_CUSTOMER_TRX_ALL
                                    WHERE BILL_TO_CUSTOMER_ID = RCTA.BILL_TO_CUSTOMER_ID)                                  
                                  ) "DATA ULTIMA COMPRA"
                                  
     ,(SELECT NVL(SUM(EXTENDED_AMOUNT),0) 
                     FROM RA_CUSTOMER_TRX_LINES_ALL
                    WHERE LINE_TYPE = 'LINE'
                      AND CUSTOMER_TRX_ID = (SELECT CUSTOMER_TRX_ID
                                               FROM RA_CUSTOMER_TRX_ALL
                                              WHERE CREATION_DATE = (SELECT MIN(CREATION_DATE)
                                                                       FROM RA_CUSTOMER_TRX_ALL
                                                                       WHERE BILL_TO_CUSTOMER_ID = RCTA.BILL_TO_CUSTOMER_ID)
                                                AND BILL_TO_CUSTOMER_ID = RCTA.BILL_TO_CUSTOMER_ID
                                                AND ROWNUM = 1)) "VALOR PRIMEIRA COMPRA"
     ,(SELECT NVL(SUM(EXTENDED_AMOUNT),0) 
                     FROM RA_CUSTOMER_TRX_LINES_ALL
                    WHERE LINE_TYPE = 'LINE'
                      AND CUSTOMER_TRX_ID = (SELECT CUSTOMER_TRX_ID
                                               FROM RA_CUSTOMER_TRX_ALL
                                              WHERE CREATION_DATE = (SELECT MAX(CREATION_DATE)
                                                                       FROM RA_CUSTOMER_TRX_ALL
                                                                       WHERE BILL_TO_CUSTOMER_ID = RCTA.BILL_TO_CUSTOMER_ID)
   AND BILL_TO_CUSTOMER_ID = RCTA.BILL_TO_CUSTOMER_ID
                                                AND ROWNUM = 1)) "VALOR ULTIMA COMPRA"

    ,(select jbacdsv.bank_instruction_code1||'-'||jbacdsv.bank_instruction_code1_dsp||' - '||jbacdsv.bank_instruction_code2||'-'||jbacdsv.bank_instruction_code2_dsp
      from JL_BR_AR_COLL_DOCS_SAB_V jbacdsv
      where jbacdsv.payment_schedule_id = APSA.payment_schedule_id
        AND jbacdsv.CUSTOMER_TRX_ID = RCTA.CUSTOMER_TRX_ID
        AND ROWNUM = 1) "INSTRUCAO BANCARIA"
    ,APSA.ATTRIBUTE3 "HISTORICO DE COBRANCA 1"
    ,APSA.ATTRIBUTE4 "HISTORICO DE COBRANCA 2"    
    ,JRS.SALESREP_NUMBER||' - '||JRS.name REPRESENTANTE
    --,XXPPG_QP_SOURCING_FIELDS_PKG.Get_SALESREP_MANAGER_INFO(XXPPG_QP_SOURCING_FIELDS_PKG.Get_SALESREP_INFO(RCTA.PRIMARY_SALESREP_ID,'grup.group_id','srep.salesrep_id'),'srep.salesrep_number||''-''||srep.name','grup.group_id') GERENTE
    ,XXPPG_QP_SOURCING_FIELDS_PKG.Get_SALESREP_MANAGER(RCTA.PRIMARY_SALESREP_ID) GERENTE
    ,HCPROF.CREDIT_CLASSIFICATION CATEGORIA                                                                                                                                                                         

    ,APSA.STATUS STATUS_NOTA_TITULO
      
FROM AR.RA_CUSTOMER_TRX_ALL       RCTA,
          --MTL_SYSTEM_ITEMS_B        MSIB,
          APPS.AR_CUSTOMERS              ACUS,
          AR.RA_CUSTOMER_TRX_LINES_ALL RCTLA,
          AR.RA_BATCH_SOURCES_ALL RBSA,
          AR.AR_PAYMENT_SCHEDULES_ALL  APSA,
          AR.RA_CUST_TRX_TYPES_ALL     RCTTA,
          AR.HZ_CUST_ACCT_SITES_ALL    HCASA,      
          
          JTF.JTF_RS_SALESREPS JRS,
          JTF.JTF_RS_RESOURCE_EXTNS JRR,
          
          AR.HZ_CUST_ACCOUNTS HCA,
          AR.HZ_PARTY_SITES HPS,
          AR.HZ_PARTIES HP,
          AR.HZ_LOCATIONS HL,
          AR.HZ_CONTACT_POINTS HCP,
          AR.HZ_CUST_SITE_USES_ALL HCSUA,
          AR.HZ_CUSTOMER_PROFILES HCPROF,   
          AR.HZ_CUST_PROFILE_AMTS HCPA       

WHERE RCTLA.SHIP_TO_CUSTOMER_ID = ACUS.CUSTOMER_ID(+)
  AND HCASA.CUST_ACCOUNT_ID = ACUS.CUSTOMER_ID
  --AND RCTLA.INVENTORY_ITEM_ID = MSIB.INVENTORY_ITEM_ID
  AND RCTLA.CUSTOMER_TRX_ID = RCTA.CUSTOMER_TRX_ID
  AND APSA.CUSTOMER_TRX_ID(+) = RCTA.CUSTOMER_TRX_ID
  AND RCTA.CUST_TRX_TYPE_ID = RCTTA.CUST_TRX_TYPE_ID  
  AND RBSA.BATCH_SOURCE_ID = RCTA.BATCH_SOURCE_ID  
  AND RCTA.PRIMARY_SALESREP_ID = JRS.SALESREP_ID(+)
  AND JRS.RESOURCE_ID = JRR.RESOURCE_ID(+)      
  AND HP.PARTY_ID = HCA.PARTY_ID
  AND HPS.PARTY_ID = HP.PARTY_ID
  AND HPS.LOCATION_ID = HL.LOCATION_ID
  --AND APSA.CUSTOMER_SITE_USE_ID = RCTA.BILL_TO_SITE_USE_ID
  --AND APSA.CUSTOMER_ID = RCTA.BILL_TO_CUSTOMER_ID
  AND HCA.CUST_ACCOUNT_ID = APSA.CUSTOMER_ID  
  AND HCP.OWNER_TABLE_NAME (+) = 'HZ_PARTIES'
  AND HCP.OWNER_TABLE_ID (+) = HP.PARTY_ID
  AND HCP.CONTACT_POINT_TYPE (+) = 'PHONE'  
  AND HCSUA.SITE_USE_CODE (+) = 'BILL_TO'
  AND HCSUA.CUST_ACCT_SITE_ID (+) = HCASA.CUST_ACCT_SITE_ID  
  AND HCPROF.PARTY_ID = HP.PARTY_ID
  AND HCPROF.CUST_ACCOUNT_ID = -1
  AND HCPA.CUST_ACCOUNT_PROFILE_ID = HCPROF.CUST_ACCOUNT_PROFILE_ID