SELECT --PPF.PERSON_ID,
        PPF.LAST_NAME NOME,
        PPF.EMPLOYEE_NUMBER MATRICULA,
        FNU.USER_NAME USUARIO,
        --PPF.EMAIL_ADDRESS,
        --PPV.JOB_NAME CARGO,
        --PPV.NAME POSICAO,
        PAA.ASS_ATTRIBUTE_CATEGORY CONTEXTO,
        PAA.ASS_ATTRIBUTE11 "PO Req.Compras Produtivas",
        PAA.ASS_ATTRIBUTE12 "PO Req.Compras Nao Produtivas",
        PAA.ASS_ATTRIBUTE13 "PO Ordem Compras",
        PAA.ASS_ATTRIBUTE19 "PO Acordos de Compra",
        PAA.ASS_ATTRIBUTE14 "PO O C Consultant Contracts",
        PAA.ASS_ATTRIBUTE15 "AP Prepay Brokers",
        PAA.ASS_ATTRIBUTE16 "AP Prepay Outros",
        PAA.ASS_ATTRIBUTE17 "PO Req.Interna Todos",
        PAA.ASS_ATTRIBUTE18 "AR Credit Notes Nivel",
        PAA.ASS_ATTRIBUTE20 "OM Canal de Vendas",
        SUP.NOME NOME_SUPERVISOR,
        SUP.MATRICULA MATRICULA_SUP,
        SUP.USER_NAME USUARIO_SUP
        --SUP.CARGO CARGO_SUPERVISOR,
        --SUP.POSICAO POSICAO_SUPERVISOR,
        --SUP.POSITION_ID POSICAO_SUP,
        --SUP.JOB_ID JOB_SUP,
        --PAA.JOB_ID,
        --PAA.POSITION_ID,
        --PPF.PARTY_ID,
        --PPF.EFFECTIVE_END_DATE,
        --PPF.EFFECTIVE_START_DATE
   FROM APPS.PER_PEOPLE_F PPF,
        APPS.PER_ALL_ASSIGNMENTS_F PAA,
        APPS.PER_POSITIONS_V PPV,
        APPS.FND_USER FNU,
        (SELECT PAA.POSITION_ID,PAA.JOB_ID,PPF.PERSON_ID,PPF.LAST_NAME NOME,PPF.EMPLOYEE_NUMBER MATRICULA,FNU.USER_NAME,PPV.JOB_NAME CARGO,PPV.NAME POSICAO
           FROM APPS.PER_PEOPLE_F PPF,APPS.PER_ALL_ASSIGNMENTS_F PAA,APPS.PER_POSITIONS_V PPV,APPS.FND_USER FNU
          WHERE PPF.PERSON_ID = PAA.PERSON_ID(+) AND PAA.JOB_ID = PPV.JOB_ID(+) AND PAA.POSITION_ID = PPV.POSITION_ID(+) AND PPF.PERSON_ID = FNU.EMPLOYEE_ID(+) AND PAA.EFFECTIVE_END_DATE > SYSDATE AND PPF.EFFECTIVE_END_DATE > SYSDATE
        ) SUP
  WHERE PPF.PERSON_ID = PAA.PERSON_ID(+)
    AND PAA.JOB_ID = PPV.JOB_ID(+)
    AND PAA.POSITION_ID = PPV.POSITION_ID(+)
    AND PAA.EFFECTIVE_END_DATE > SYSDATE
    AND PPF.EFFECTIVE_END_DATE > SYSDATE
    AND PAA.SUPERVISOR_ID = SUP.PERSON_ID(+)
    AND PPF.PERSON_ID = FNU.EMPLOYEE_ID
  --AND PPF.FULL_NAME LIKE ('MICHELE%FERNAN%')
  --AND PPF.PERSON_ID IN(1545,1371,1489,6830)
  --AND PPF.EMPLOYEE_NUMBER = '270853'
  --AND SUP.MATRICULA IS NULL
  --AND PPF.PERSON_ID = 18391
  --AND PAA.POSITION_ID = 2076 --3129
ORDER BY PPF.LAST_NAME