select distinct
    hca.cust_account_id,
    hcasa.cust_acct_site_id,
    hcasa.party_site_id,
    hcasa.orig_system_reference,
    hcsua.site_use_id,
    hcsua.ship_via,
    hcsua.attribute4,
    hcsua.attribute7,
    hcsua.warehouse_id,
    hp.party_name "cliente", 
    substr(hcsua.location,1,instr(hcsua.location,'_',1)-1) "cnpj",
    hcsua.site_use_code,
    hl.city "cidade",
    hl.state "estado",
    hl.address4 "bairro",
    (select name from apps.ra_terms_tl where term_id = hcsua.payment_term_id and language = 'PTB') "condicao_pagamento", 
    (select description from apps.ra_terms_tl where term_id = hcsua.payment_term_id and language = 'PTB') "descricao_cond_pagamento",
    (select distinct ship_method_code_meaning  from apps.wsh_carrier_ship_methods_v where ship_method_code = hcsua.ship_via) "metodo_entrega", 
    (select name from apps.oe_transaction_types_tl where transaction_type_id = hcsua.order_type_id and language = 'PTB') "tipo_ordem", 
    (select name from apps.qp_list_headers_all where list_header_id = hcsua.price_list_id) "lista_preco", 
    hcsua.freight_term "tipo_frete", 
    (select salesrep_number from apps.jtf_rs_salesreps where salesrep_id = hcsua.primary_salesrep_id) "vendedor",
    demand_class_code "classe_demanda",
    (select organization_code from apps.mtl_parameters where organization_id = hcsua.warehouse_id) "deposito",
    hp.attribute1 "perfil_porte",
    hp.attribute2 "grupo_cliente",
    hp.attribute3 "ramo_atividade",
    hp.attribute4 "grupo_pbc",
    hp.attribute6 "contrato",
    substr(hp.attribute7,1,10) "data_inicio_contrato", 
    hcsua.attribute1 "canal_vendas",
    hps.attribute10 "isento_cas",
    hps.attribute1 "cas_1",
    hps.attribute2 "cas_2",
    hps.attribute3 "cas_3",
    hps.attribute4 "cas_4",
    hps.attribute5 "cas_5",
    hps.attribute6 "cas_6",
    hps.attribute7 "cas_7",
    hps.attribute8 "assinatura_cas",
    hps.attribute9 "validade_cas",
    hps.attribute11 "area_metrop",
    hps.attribute12 "micro_ibge",
    hps.attribute13 macro_ibge,
    hps.attribute14 regiao_geografica,
    hps.attribute15 grupo_compras,
    hps.attribute16 sub_ramo_ativ,
    hps.attribute17 regiao_demanda,
    hps.attribute18 grupo_pbc,
    hps.attribute19 rede,
    hcsua.attribute2 data_1ro_faturamento,
    hcsua.attribute3 percent_comissao,
    hcsua.attribute4 local_end_terceiro,
    substr(hcsua.attribute6,1,10) data_implantacao,
    hcsua.attribute7 prioridade_entrega,
    hcsua.attribute8 valor_minimo_fat,
    hcsua.attribute9 vol_ultimo_trimestre,
    hcsua.attribute10 vol_penultimo_trimestre,
    hcsua.attribute11 vol_data_vigencia,
    hcsua.attribute12 vol_mix_produtos,
    --hcp.global_attribute1 remit_protest_instructions,
    --hcp.global_attribute2 remit_interest_instructions,
    hcasa.global_attribute1 nome_empresa,
    hcasa.global_attribute2 tipo_inscrição,
    hcasa.global_attribute3 número_inscrição,
    hcasa.global_attribute4 agência_inscrição,
    hcasa.global_attribute5 dígito_inscrição,
    hcasa.global_attribute6 inscrição_estadual,
    hcasa.global_attribute7 inscrição_municipal,
    hcasa.global_attribute8 classe_contribuinte,
    hcasa.global_attribute9 usar_perfil_local_cliente,
    hcasa.global_attribute10 número_inscr_suframa,
    hcasa.global_attribute11 indicador_natureza_ret_imposto,
    hcasa.global_attribute12  sujeito_cfop_zona_franca
from 
    apps.hz_parties hp,
    apps.hz_cust_accounts hca,
    apps.hz_cust_site_uses_all hcsua,
    apps.hz_cust_acct_sites_all hcasa,
    apps.hz_party_sites hps,
    apps.hz_locations hl,
    --apps.hz_customer_profiles hcp,
    apps.hz_contact_points hzcp
where hcsua.cust_acct_site_id = hcasa.cust_acct_site_id
  and hcasa.party_site_id = hps.party_site_id
  and hps.party_id = hp.party_id
  and hp.party_id = hca.party_id
  and hps.location_id = hl.location_id
  --and hca.cust_account_id = hcp.cust_account_id
  --and hcsua.site_use_id = hcp.site_use_id
  and hcsua.site_use_code = 'SHIP_TO'
  --and hps.party_site_id in(20851)
  and hps.party_site_id = hzcp.owner_table_id(+)
  and nvl(hzcp.primary_flag(+),'Y') = 'Y'
  and nvl(hzcp.contact_point_type(+),'EMAIL') = 'EMAIL'
  and nvl(hzcp.owner_table_name(+),'HZ_PARTY_SITES') = 'HZ_PARTY_SITES'