SELECT GOD.ORGANIZATION_CODE ORGANIZACAO,
       MSIB.SEGMENT1 ITEM,
       MSIB.SEGMENT1 || ' - ' || MSIB.DESCRIPTION "DECRICAO DO ITEM",
       MCBI.SEGMENT1 "CATEGORIA INVENTARIO SEG1",
       MCBI.SEGMENT2 "CATEGORIA INVENTARIO SEG2",
       MCBI.SEGMENT3 "CATEGORIA INVENTARIO SEG3",
       NVL(GPB.PRIMARY_QUANTITY, 0) "QUANTIDADE ESTOQUE",
        GPS.PERIOD_CODE MES               
       ,GPS.CALENDAR_CODE ANO
       , 'STANDARD' TIPO_CUSTO     
       ,(SELECT SUM(CCD.CMPNT_COST) 
                 FROM APPS.CM_CMPT_DTL CCD
               WHERE CCD.COST_TYPE_ID = GPS.COST_TYPE_ID
               AND   CCD.INVENTORY_ITEM_ID = MSIB.INVENTORY_ITEM_ID
               AND   CCD.ORGANIZATION_ID = MSIB.ORGANIZATION_ID
               AND   CCD.PERIOD_ID = GPS.PERIOD_ID) CUSTO_UNIT
      --
     ,(SELECT SUM(CCD.CMPNT_COST) 
                 FROM APPS.CM_CMPT_DTL CCD
               WHERE CCD.COST_TYPE_ID = GPS.COST_TYPE_ID
               AND   CCD.INVENTORY_ITEM_ID = MSIB.INVENTORY_ITEM_ID
               AND   CCD.ORGANIZATION_ID = MSIB.ORGANIZATION_ID
               AND   CCD.PERIOD_ID = GPS.PERIOD_ID)*   NVL(GPB.PRIMARY_QUANTITY, 0) TOTAL
       ,GPB.SUBINVENTORY_CODE "SUB INVENTARIO",
        GPB.LOT_NUMBER        LOTE 
  FROM APPS.GMF_PERIOD_STATUSES          GPS,
       APPS.MTL_SYSTEM_ITEMS_B           MSIB,
       APPS.GMF_ORGANIZATION_DEFINITIONS GOD,
       apps.GMF_PERIOD_BALANCES          GPB,
       APPS.ORG_ACCT_PERIODS             OAP,
       APPS.MTL_CATEGORIES_B             MCBI,
       APPS.MTL_CATEGORY_SETS            MCSI,
       APPS.MTL_ITEM_CATEGORIES          MICI,
       APPS.ORG_ORGANIZATION_DEFINITIONS               MP
 WHERE MSIB.ORGANIZATION_ID = GOD.ORGANIZATION_ID
   AND GPB.ORGANIZATION_ID = MSIB.ORGANIZATION_ID
   AND GPB.INVENTORY_ITEM_ID = MSIB.INVENTORY_ITEM_ID
   AND OAP.ACCT_PERIOD_ID = GPB.ACCT_PERIOD_ID
   AND OAP.ORGANIZATION_ID = MSIB.ORGANIZATION_ID
   AND TRUNC(OAP.PERIOD_START_DATE) = TRUNC(GPS.START_DATE)
   AND TRUNC(OAP.SCHEDULE_CLOSE_DATE) = TRUNC(GPS.END_DATE)
   AND MCBI.STRUCTURE_ID = MCSI.STRUCTURE_ID
   AND MCSI.CATEGORY_SET_ID = 1
   AND MICI.CATEGORY_SET_ID = MCSI.CATEGORY_SET_ID
   AND MICI.INVENTORY_ITEM_ID = MSIB.INVENTORY_ITEM_ID
   AND MICI.ORGANIZATION_ID = MSIB.ORGANIZATION_ID
   AND MICI.CATEGORY_ID = MCBI.CATEGORY_ID
   AND GPS.DELETE_MARK = 0
   AND GPS.LEGAL_ENTITY_ID = MP.LEGAL_ENTITY
   AND GPS.COST_TYPE_ID = 1005    --STANDARD
   AND MSIB.PROCESS_COSTING_ENABLED_FLAG = 'Y'
   AND MP.ORGANIZATION_ID = MSIB.ORGANIZATION_ID

UNION
   SELECT GOD.ORGANIZATION_CODE ORGANIZACAO,
       MSIB.SEGMENT1 ITEM,
       MSIB.SEGMENT1 || ' - ' || MSIB.DESCRIPTION "DESCRICAO DO ITEM",
       MCBI.SEGMENT1 "CATEGORIA INVENTARIO SEG1",
       MCBI.SEGMENT2 "CATEGORIA INVENTARIO SEG2",
       MCBI.SEGMENT3 "CATEGORIA INVENTARIO SEG3",
       NVL(GPB.PRIMARY_QUANTITY, 0) "QUANTIDADE ESTOQUE",
        GPS.PERIOD_CODE MES               
       ,GPS.CALENDAR_CODE ANO
       , 'MEDIO' TIPO_CUSTO     
       ,(SELECT SUM(CCD.CMPNT_COST) 
                 FROM APPS.CM_CMPT_DTL CCD
               WHERE CCD.COST_TYPE_ID = GPS.COST_TYPE_ID
               AND   CCD.INVENTORY_ITEM_ID = MSIB.INVENTORY_ITEM_ID
               AND   CCD.ORGANIZATION_ID = MSIB.ORGANIZATION_ID
               AND   CCD.PERIOD_ID = GPS.PERIOD_ID) CUSTO_UNIT
      --
     ,(SELECT SUM(CCD.CMPNT_COST) 
                 FROM APPS.CM_CMPT_DTL CCD
               WHERE CCD.COST_TYPE_ID = GPS.COST_TYPE_ID
               AND   CCD.INVENTORY_ITEM_ID = MSIB.INVENTORY_ITEM_ID
               AND   CCD.ORGANIZATION_ID = MSIB.ORGANIZATION_ID
               AND   CCD.PERIOD_ID = GPS.PERIOD_ID)*   NVL(GPB.PRIMARY_QUANTITY, 0) TOTAL
       ,GPB.SUBINVENTORY_CODE "SUB INVENTARIO",
        GPB.LOT_NUMBER        LOTE 
  FROM APPS.GMF_PERIOD_STATUSES          GPS,
       APPS.MTL_SYSTEM_ITEMS_B           MSIB,
       APPS.GMF_ORGANIZATION_DEFINITIONS GOD,
       apps.GMF_PERIOD_BALANCES          GPB,
       APPS.ORG_ACCT_PERIODS             OAP,
       APPS.MTL_CATEGORIES_B             MCBI,
       APPS.MTL_CATEGORY_SETS            MCSI,
       APPS.MTL_ITEM_CATEGORIES          MICI,
       APPS.ORG_ORGANIZATION_DEFINITIONS               MP
 WHERE MSIB.ORGANIZATION_ID = GOD.ORGANIZATION_ID
   AND GPB.ORGANIZATION_ID = MSIB.ORGANIZATION_ID
   AND GPB.INVENTORY_ITEM_ID = MSIB.INVENTORY_ITEM_ID
   AND OAP.ACCT_PERIOD_ID = GPB.ACCT_PERIOD_ID
   AND OAP.ORGANIZATION_ID = MSIB.ORGANIZATION_ID
   AND TRUNC(OAP.PERIOD_START_DATE) = TRUNC(GPS.START_DATE)
   AND TRUNC(OAP.SCHEDULE_CLOSE_DATE) = TRUNC(GPS.END_DATE)
   AND MCBI.STRUCTURE_ID = MCSI.STRUCTURE_ID
   AND MCSI.CATEGORY_SET_ID = 1
   AND MICI.CATEGORY_SET_ID = MCSI.CATEGORY_SET_ID
   AND MICI.INVENTORY_ITEM_ID = MSIB.INVENTORY_ITEM_ID
   AND MICI.ORGANIZATION_ID = MSIB.ORGANIZATION_ID
   AND MICI.CATEGORY_ID = MCBI.CATEGORY_ID
   AND GPS.DELETE_MARK = 0
   AND GPS.LEGAL_ENTITY_ID = MP.LEGAL_ENTITY
   AND GPS.COST_TYPE_ID = 1000    --MEDIO
   AND MSIB.PROCESS_COSTING_ENABLED_FLAG = 'Y'
   AND MP.ORGANIZATION_ID = MSIB.ORGANIZATION_ID
ORDER BY 1,2,5,6, 10

