SELECT GOD.ORGANIZATION_CODE ORGANIZACAO  
, MSIB.SEGMENT1 ITEM
, MSIB.SEGMENT1||' - '|| MSIB.DESCRIPTION "DECRICAO DO ITEM"
, MCBI.SEGMENT1 "CATEGORIA INVENTARIO SEG1"
, MCBI.SEGMENT2 "CATEGORIA INVENTARIO SEG2"
, MCBI.SEGMENT3 "CATEGORIA INVENTARIO SEG3"
, NVL(GPB.PRIMARY_QUANTITY,0) "QUANTIDADE ESTOQUE"  
, GPS.PERIOD_CODE MES               
       , GPS.CALENDAR_CODE ANO
       , 'STANDARD' TIPO_CUSTO
       , TO_CHAR(SUM(CCD.CMPNT_COST),'999G999G990D000000000') "CUSTO UNIT"   
       , TO_CHAR(SUM(CCD.CMPNT_COST * NVL(GPB.PRIMARY_QUANTITY,0)),'999G999G990D000000000') TOTAL       
        , GPB.SUBINVENTORY_CODE "SUB INVENTARIO"
        , GPB.LOT_NUMBER LOTE                 
    FROM APPS.CM_CMPT_DTL CCD       
       , APPS.GMF_PERIOD_STATUSES GPS       
       , APPS.MTL_SYSTEM_ITEMS_B MSIB
       , APPS.GMF_ORGANIZATION_DEFINITIONS GOD                                   
       , (SELECT COST_TYPE_ID FROM apps.CM_MTHD_MST WHERE COST_MTHD_CODE = 'STD' AND ROWNUM = 1)   STD        
       ,apps.GMF_PERIOD_BALANCES GPB               
       ,APPS.ORG_ACCT_PERIODS OAP     
       , APPS.MTL_CATEGORIES_B MCBI
       , APPS.MTL_CATEGORY_SETS MCSI
       , APPS.MTL_ITEM_CATEGORIES MICI       
   WHERE MSIB.ORGANIZATION_ID = GOD.ORGANIZATION_ID  
     and CCD.COST_TYPE_ID (+) = STD.COST_TYPE_ID 
     AND CCD.INVENTORY_ITEM_ID = MSIB.INVENTORY_ITEM_ID
     AND CCD.ORGANIZATION_ID = MSIB.ORGANIZATION_ID
     --AND GPS.PERIOD_ID = GPB.ACCT_PERIOD_ID 
     AND CCD.PERIOD_ID = GPS.PERIOD_ID     
     AND CCD.DELETE_MARK = 0                                   
     AND GPS.DELETE_MARK = 0                
     AND GPB.ORGANIZATION_ID = MSIB.ORGANIZATION_ID
     AND GPB.INVENTORY_ITEM_ID  = MSIB.INVENTORY_ITEM_ID      
     AND OAP.ACCT_PERIOD_ID  = GPB.ACCT_PERIOD_ID
     AND OAP.ORGANIZATION_ID  = MSIB.ORGANIZATION_ID 
     AND TRUNC(OAP.PERIOD_START_DATE) = TRUNC(GPS.START_DATE)
     AND TRUNC(OAP.SCHEDULE_CLOSE_DATE) = TRUNC(GPS.END_DATE)     
     AND MCBI.STRUCTURE_ID = MCSI.STRUCTURE_ID             
     AND MCSI.CATEGORY_SET_ID = (SELECT category_set_id FROM apps.mtl_default_category_sets WHERE functional_area_id = 1)
     AND MICI.CATEGORY_SET_ID = MCSI.CATEGORY_SET_ID
     AND MICI.INVENTORY_ITEM_ID = MSIB.INVENTORY_ITEM_ID
     AND MICI.ORGANIZATION_ID = MSIB.ORGANIZATION_ID
     AND MICI.CATEGORY_ID = MCBI.CATEGORY_ID                
GROUP BY GPS.PERIOD_CODE
        ,GPS.CALENDAR_CODE
        ,GOD.ORGANIZATION_CODE  
        , MSIB.SEGMENT1 
        , MSIB.SEGMENT1||' - '|| MSIB.DESCRIPTION    
        , MCBI.SEGMENT1 
        , MCBI.SEGMENT2
        , MCBI.SEGMENT3
        ,NVL(GPB.PRIMARY_QUANTITY,0) 
        , GPB.SUBINVENTORY_CODE
        , GPB.LOT_NUMBER  
union
SELECT GOD.ORGANIZATION_CODE ORGANIZACAO  
, MSIB.SEGMENT1 ITEM
, MSIB.SEGMENT1||' - '|| MSIB.DESCRIPTION "DECRICAO DO ITEM"
, MCBI.SEGMENT1 "CATEGORIA INVENTARIO SEG1"
, MCBI.SEGMENT2 "CATEGORIA INVENTARIO SEG2"
, MCBI.SEGMENT3 "CATEGORIA INVENTARIO SEG3"
, NVL(GPB.PRIMARY_QUANTITY,0) "QUANTIDADE ESTOQUE"  
, GPS.PERIOD_CODE MES               
       , GPS.CALENDAR_CODE ANO
       , 'MEDIO' TIPO_CUSTO      
      , TO_CHAR(SUM(CCD.CMPNT_COST),'999G999G990D000000000') "CUSTO UNIT" 
      , TO_CHAR(SUM(CCD.CMPNT_COST * NVL(GPB.PRIMARY_QUANTITY,0)),'999G999G990D000000000') TOTAL       
        , GPB.SUBINVENTORY_CODE "SUB INVENTARIO"
        , GPB.LOT_NUMBER LOTE                 
    FROM APPS.CM_CMPT_DTL CCD              
       , APPS.GMF_PERIOD_STATUSES GPS       
       , APPS.MTL_SYSTEM_ITEMS_B MSIB
       , APPS.GMF_ORGANIZATION_DEFINITIONS GOD                                   
       , (SELECT COST_TYPE_ID FROM apps.CM_MTHD_MST WHERE COST_MTHD_CODE = 'PMAC' AND ROWNUM = 1)  PMAC        
       ,apps.GMF_PERIOD_BALANCES GPB           
       ,APPS.ORG_ACCT_PERIODS OAP     
       , APPS.MTL_CATEGORIES_B MCBI
       , APPS.MTL_CATEGORY_SETS MCSI
       , APPS.MTL_ITEM_CATEGORIES MICI       
   WHERE MSIB.ORGANIZATION_ID = GOD.ORGANIZATION_ID  
     and CCD.COST_TYPE_ID (+) = PMAC.COST_TYPE_ID 
     AND CCD.INVENTORY_ITEM_ID = MSIB.INVENTORY_ITEM_ID
     AND CCD.ORGANIZATION_ID = MSIB.ORGANIZATION_ID
     --AND GPS.PERIOD_ID = GPB.ACCT_PERIOD_ID 
     AND CCD.PERIOD_ID = GPS.PERIOD_ID     
     AND CCD.DELETE_MARK = 0                                   
     AND GPS.DELETE_MARK = 0                
     AND GPB.ORGANIZATION_ID = MSIB.ORGANIZATION_ID
     AND GPB.INVENTORY_ITEM_ID  = MSIB.INVENTORY_ITEM_ID         
     AND OAP.ACCT_PERIOD_ID  = GPB.ACCT_PERIOD_ID
     AND OAP.ORGANIZATION_ID  = MSIB.ORGANIZATION_ID 
     AND TRUNC(OAP.PERIOD_START_DATE) = TRUNC(GPS.START_DATE)
     AND TRUNC(OAP.SCHEDULE_CLOSE_DATE) = TRUNC(GPS.END_DATE)        
     AND MCBI.STRUCTURE_ID = MCSI.STRUCTURE_ID             
     AND MCSI.CATEGORY_SET_ID = (SELECT category_set_id FROM apps.mtl_default_category_sets WHERE functional_area_id = 1)
     AND MICI.CATEGORY_SET_ID = MCSI.CATEGORY_SET_ID
     AND MICI.INVENTORY_ITEM_ID = MSIB.INVENTORY_ITEM_ID
     AND MICI.ORGANIZATION_ID = MSIB.ORGANIZATION_ID
     AND MICI.CATEGORY_ID = MCBI.CATEGORY_ID           
GROUP BY GPS.PERIOD_CODE
        ,GPS.CALENDAR_CODE
        ,GOD.ORGANIZATION_CODE  
        , MSIB.SEGMENT1 
        , MSIB.SEGMENT1||' - '|| MSIB.DESCRIPTION           
        , MCBI.SEGMENT1
        , MCBI.SEGMENT2
        , MCBI.SEGMENT3                        
        ,NVL(GPB.PRIMARY_QUANTITY,0) 
        , GPB.SUBINVENTORY_CODE
        , GPB.LOT_NUMBER           
ORDER BY 1,2,5,6